// Generated by scripts/build-client.mjs from src/client/. Edit those files.
//
// dsh-aire-memory — Aire 记忆（Client）: 右栏快捷面板 + 原生设置页补强。
// 客户端半边是纯 JavaScript（无 JSX、无 ESM import），React 通过闭包注入。
window.__ModuleLoader__.load({
  id: 'dsh-get-memory',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    var React = require('react')

    // Layer: identity and shared constants.
    var PACKAGE = 'dsh-get-memory'
    var STATUS_URL = '/aire-memory/status'
    var REPOS_URL = '/aire-memory/repos'
    var INIT_URL = '/aire-memory/init'
    var SESSION_URL = '/aire-memory/session'
    var PULL_URL = '/aire-memory/pull'
    var WRITEBACK_URL = '/aire-memory/writeback'
    var TOKEN_URL = '/aire-memory/token'
    var CONFIG_URL = '/aire-memory/config'
    var FILESYNC_URL = '/aire-memory/filesync'
    var TOKEN_REF = 'AIRE_MEMORY_GITHUB_TOKEN'
    var PANEL_KEY = 'aire-memory'
    var STYLE_ID = 'dsh-aire-memory-style'

    // Layer: host endpoint calls (状态 / 拉取 / 令牌 / 配置都走宿主半边端点).
    function fetchJson(url, options) {
      return fetch(url, options).then(function (response) {
        if (!response.ok) throw new Error('HTTP ' + response.status)
        return response.json()
      })
    }

    function postJson(url, payload) {
      return fetchJson(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })
    }

    function fetchStatus() {
      return fetchJson(STATUS_URL)
    }

    function fetchRepos() {
      return fetchJson(REPOS_URL)
    }

    function initRepo() {
      return fetchJson(INIT_URL, { method: 'POST' })
    }

    function fetchSessionEnabled(session) {
      return fetchJson(SESSION_URL + '?session=' + encodeURIComponent(session || ''))
    }

    function setSessionEnabled(session, enabled) {
      return postJson(SESSION_URL + '?session=' + encodeURIComponent(session || ''), { enabled: enabled })
    }

    function checkUpdate() {
      return fetch('https://registry.npmjs.org/dsh-get-memory/latest')
        .then(function (response) {
          if (!response.ok) throw new Error('HTTP ' + response.status)
          return response.json()
        })
    }

    function triggerPull() {
      return fetchJson(PULL_URL, { method: 'POST' })
    }

    function saveToken(value) {
      return postJson(TOKEN_URL, { token: value })
    }

    function updateConfig(patch) {
      return postJson(CONFIG_URL, { patch: patch })
    }

    function syncFiles() {
      return fetchJson(FILESYNC_URL)
    }

    function saveFileModes(modes) {
      return postJson(FILESYNC_URL, { modes: modes })
    }

    function formatTime(iso) {
      if (!iso) return '—'
      var date = new Date(iso)
      if (Number.isNaN(date.getTime())) return String(iso)
      var pad = function (n) { return n < 10 ? '0' + n : String(n) }
      return date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate())
        + ' ' + pad(date.getHours()) + ':' + pad(date.getMinutes())
    }

    function tokenSourceLabel(source) {
      if (source === 'credentials') return '凭据库'
      if (source === 'env') return '环境变量'
      if (source === 'config') return '插件配置'
      return '其他来源'
    }

    function statusTone(status) {
      if (status === 'ok') return 'ok'
      if (status === 'error') return 'error'
      if (status === 'skip') return 'skip'
      return 'warn'
    }

    // Layer: package stylesheet (plain <style> tag, removed on unload).
    var PANEL_CSS = [
      '.am-panel{display:flex;flex-direction:column;gap:14px;padding:20px;height:100%;overflow-y:auto;box-sizing:border-box;width:100%;max-width:780px;margin:0 auto}',
      '.am-card{background:color-mix(in srgb, var(--ds-color-bg-card,#ffffff) 52%, transparent);backdrop-filter:blur(14px) saturate(1.15);-webkit-backdrop-filter:blur(14px) saturate(1.15);border:1px solid color-mix(in srgb, var(--ds-color-border,#e5e7eb) 62%, transparent);border-radius:14px;padding:14px 16px;box-shadow:0 6px 24px rgba(0,0,0,.06);animation:amFadeIn .28s ease both}',
      '@keyframes amFadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}',
      '.am-title{font-size:13px;font-weight:600;margin:0 0 10px;display:flex;align-items:center;gap:6px}',
      '.am-title .am-pulse{width:7px;height:7px;border-radius:50%;background:#22c55e;animation:amBreathe 2.4s ease-in-out infinite}',
      '@keyframes amBreathe{0%,100%{box-shadow:0 0 0 3px rgba(34,197,94,.18)}50%{box-shadow:0 0 0 6px rgba(34,197,94,.05)}}',
      '.am-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:6px 0}',
      '.am-label{font-size:13px;color:var(--ds-color-text-secondary,#6b7280);flex:none}',
      '.am-value{font-size:13px;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:60%}',
      '.am-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;vertical-align:middle;flex:none}',
      '.am-dot.ok{background:#22c55e}.am-dot.warn{background:#f59e0b}.am-dot.error{background:#ef4444}.am-dot.skip{background:#9ca3af}',
      '.am-history{display:flex;flex-direction:column;gap:8px;max-height:280px;overflow-y:auto}',
      '.am-history-item{font-size:12px;line-height:1.5;display:flex;gap:6px;align-items:baseline}',
      '.am-history-item>span:last-child{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
      '.am-history-time{color:var(--ds-color-text-tertiary,#9ca3af);flex:none}',
      '.am-history-kind{flex:none;font-size:11px;padding:0 5px;border-radius:4px;background:color-mix(in srgb, var(--ds-color-bg-secondary,#f3f4f6) 72%, transparent);color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-input{flex:1;min-width:0;font-size:13px;padding:6px 8px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-input,#ffffff) 60%, transparent);color:inherit;transition:border-color .15s}',
      '.am-input:focus{border-color:var(--ds-color-accent,#4f46e5);outline:none}',
      '.am-textarea{flex:1;min-width:0;font-size:13px;padding:6px 8px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-input,#ffffff) 60%, transparent);color:inherit;resize:vertical;font-family:inherit;line-height:1.5}',
      '.am-button{font-size:13px;padding:6px 12px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-secondary,#f3f4f6) 80%, transparent);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);color:inherit;cursor:pointer;transition:filter .15s,transform .05s;flex:none}',
      '.am-button:hover:not(:disabled){filter:brightness(.96)}',
      '.am-button:active:not(:disabled){transform:scale(.98)}',
      '.am-button.primary{background:var(--ds-color-accent,#4f46e5);border-color:transparent;color:#fff}',
      '.am-button.primary:hover:not(:disabled){filter:brightness(1.08)}',
      '.am-button:disabled{opacity:.55;cursor:default}',
      '.am-notice{font-size:12px;color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-empty{font-size:12px;color:var(--ds-color-text-tertiary,#9ca3af);padding:6px 0}',
      '.am-switch{position:relative;width:36px;height:20px;border-radius:999px;border:1px solid var(--ds-color-border,#e5e7eb);background:var(--ds-color-bg-secondary,#e5e7eb);cursor:pointer;flex:none;transition:background .15s}',
      '.am-switch.on{background:var(--ds-color-accent,#4f46e5);border-color:transparent}',
      '.am-switch::after{content:"";position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;background:#fff;transition:left .15s}',
      '.am-switch.on::after{left:18px}',
      '.am-switch:focus-visible{outline:2px solid var(--ds-color-accent,#4f46e5);outline-offset:2px}',
      '.am-indicator{display:inline-flex;align-items:center;gap:6px;font-size:12px;color:var(--ds-color-text-tertiary,#9ca3af);padding:2px 0}',
      '.am-indicator .am-dot{margin-right:0}',
      '.am-indicator:hover{color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-global-notice{display:inline-flex;align-items:center;gap:7px;font-size:12px;color:var(--ds-color-text-secondary,#6b7280);background:color-mix(in srgb, var(--ds-color-bg-card,#ffffff) 72%, transparent);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);border:1px solid color-mix(in srgb, var(--ds-color-border,#e5e7eb) 60%, transparent);border-radius:999px;padding:4px 12px;animation:amFadeIn .28s ease both}',
      '.am-global-notice .am-dot{margin-right:0}',
      '.am-pulse-dot{width:7px;height:7px;border-radius:50%;background:#f59e0b;flex:none;animation:amBreathe 2.4s ease-in-out infinite}',
      '.am-dock-control{display:inline-flex;align-items:center;gap:8px;flex:none}',
      '.am-dock-pill{display:inline-flex;align-items:center;border-radius:999px;border:1px solid color-mix(in srgb,var(--ds-color-border,#e5e7eb) 70%,transparent);background:color-mix(in srgb,var(--ds-color-bg-card,#ffffff) 72%,transparent);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);overflow:hidden}',
      '.am-session-toggle{font-size:12px;line-height:1;border:none;border-right:1px solid color-mix(in srgb,var(--ds-color-border,#e5e7eb) 70%,transparent);background:transparent;color:var(--ds-color-text-secondary,#6b7280);padding:5px 10px;cursor:pointer;transition:all .2s ease}',
      '.am-session-toggle:hover{color:var(--ds-color-text,#111827)}',
      '.am-session-toggle.am-on{color:#16a34a}',
      '.am-dock-pill .am-global-notice{border:none;background:none;border-radius:0;padding:4px 12px 4px 10px;animation:none}',
      '.am-menu-item{display:flex;align-items:center;gap:6px;width:100%;min-height:34px;padding:6px 8px;border:none;border-radius:8px;background:transparent;cursor:pointer;font:inherit;font-size:13px;line-height:20px;text-align:left;color:var(--ds-color-text,#111827)}',
      '.am-menu-item:hover{background:color-mix(in srgb,var(--ds-color-bg-secondary,#f3f4f6) 70%,transparent)}',
      '.am-menu-item-icon{display:inline-flex;flex:none;width:14px;height:14px;align-items:center;justify-content:center;color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-number-field{display:flex;align-items:center;gap:4px;flex:1;min-width:0}',
      '.am-number-btn{flex:none;width:24px;height:24px;border-radius:6px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb,var(--ds-color-bg-secondary,#f3f4f6) 80%,transparent);color:var(--ds-color-text,#111827);cursor:pointer;font-size:14px;line-height:1}',
      '.am-number-btn:disabled{opacity:.4;cursor:not-allowed}',
      '.am-number-input{width:64px;flex:none;text-align:center}',
      '.am-guide-banner{margin:0 0 14px;border:1px solid color-mix(in srgb,var(--ds-color-accent,#6366f1) 35%,transparent);border-radius:14px;padding:12px 14px;background:color-mix(in srgb,var(--ds-color-bg-card,#ffffff) 80%,transparent);position:relative}',
      '.am-guide-banner-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}',
      '.am-guide-banner-title{font-size:14px;font-weight:600;color:var(--ds-color-text,#111827)}',
      '.am-guide-close{border:none;background:none;font-size:18px;line-height:1;cursor:pointer;color:var(--ds-color-text-secondary,#6b7280);padding:2px 6px;border-radius:8px}',
      '.am-guide-close:hover{background:color-mix(in srgb,var(--ds-color-border,#e5e7eb) 50%,transparent)}',
      '.am-guide-close.am-disabled{opacity:.35;cursor:not-allowed}',
      '.am-guide-banner-buttons{display:flex;flex-wrap:wrap;gap:8px}',
      '.am-guide-button{font-size:12px;padding:5px 12px;border-radius:999px;border:1px solid color-mix(in srgb,var(--ds-color-accent,#6366f1) 40%,transparent);background:transparent;color:var(--ds-color-accent,#6366f1);cursor:pointer;transition:all .2s ease}',
      '.am-guide-button:hover{background:color-mix(in srgb,var(--ds-color-accent,#6366f1) 12%,transparent)}',
      '.am-guide-button.am-guide-active{background:color-mix(in srgb,var(--ds-color-accent,#6366f1) 18%,transparent);font-weight:600}',
      '.am-guide-mask{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.4);display:flex;align-items:center;justify-content:center;padding:24px}',
      '.am-guide-modal{max-width:520px;width:100%;max-height:76vh;overflow:auto;background:var(--ds-color-bg-card,#ffffff);color:var(--ds-color-text,#111827);border-radius:16px;padding:18px 20px;box-shadow:0 20px 60px rgba(0,0,0,.25)}',
      '.am-guide-modal-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}',
      '.am-guide-modal-title{font-size:16px;font-weight:600}',
      '.am-guide-modal-body{font-size:13px;line-height:1.8;white-space:pre-wrap;color:var(--ds-color-text,#111827)}',
      '.am-link{font-size:13px;color:var(--ds-color-accent,#6366f1);text-decoration:none;margin-right:16px}',
      '.am-link:hover{text-decoration:underline}',
      '.am-changelog{margin-top:10px;font-size:13px;color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-changelog summary{cursor:pointer;color:var(--ds-color-text,#111827);font-weight:500}',
      '.am-changelog-body{margin-top:8px;display:flex;flex-direction:column;gap:6px}',
      '.am-changelog-row{display:flex;gap:10px;align-items:baseline}',
      '.am-changelog-ver{font-family:monospace;color:var(--ds-color-accent,#6366f1);flex:none}',
      '.am-toast-root{position:fixed;top:18px;left:50%;transform:translateX(-50%);z-index:2147483000;display:flex;flex-direction:column;align-items:center;gap:8px;pointer-events:none;width:max-content;max-width:82vw}',
      '.am-toast{font-size:13px;line-height:1.5;padding:9px 16px;border-radius:12px;background:var(--ds-color-bg-card,#ffffff);color:var(--ds-color-text,#111827);border:1px solid color-mix(in srgb,var(--ds-color-border,#e5e7eb) 70%,transparent);box-shadow:0 10px 32px rgba(0,0,0,.16);animation:amToastIn .25s ease both}',
      '.am-toast.warn{border-color:color-mix(in srgb,#f59e0b 45%,transparent)}',
      '.am-toast.ok{border-color:color-mix(in srgb,#16a34a 45%,transparent)}',
      '.am-toast.error{border-color:color-mix(in srgb,#ef4444 45%,transparent)}',
      '@keyframes amToastIn{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}',
      '.am-settings{padding-bottom:16px}',
      '.am-save-bar{position:sticky;bottom:0;z-index:30;display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:14px;padding:10px 16px;border-radius:14px;border:1px solid color-mix(in srgb,var(--ds-color-border,#e5e7eb) 60%,transparent);background:color-mix(in srgb,var(--ds-color-bg-card,#ffffff) 82%,transparent);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);box-shadow:0 -6px 20px rgba(0,0,0,.08)}',
      '.am-save-hint{font-size:12px;color:var(--ds-color-text-secondary,#6b7280);margin-right:auto}',
    ].join('\n')

    function installStyles() {
      if (document.getElementById(STYLE_ID)) return function () {}
      var tag = document.createElement('style')
      tag.id = STYLE_ID
      tag.setAttribute('data-dyn', PACKAGE)
      tag.textContent = PANEL_CSS
      document.head.append(tag)
      return function () { tag.remove() }
    }

    // Layer: panel icon and the main Aire 记忆 panel.
    function AireIcon(props) {
      var size = props && props.size ? props.size : 20
      var active = !!(props && props.active)
      return React.createElement(
        'svg',
        {
          width: size, height: size, viewBox: '0 0 24 24', fill: 'none',
          'aria-hidden': 'true',
        },
        React.createElement('path', {
          d: 'M12 21s-7.5-4.6-9.7-9.3C.7 8.3 2.7 4.5 6.3 4.5c2.2 0 3.7 1.2 5.7 3.4 2-2.2 3.5-3.4 5.7-3.4 3.6 0 5.6 3.8 4 7.2C19.5 16.4 12 21 12 21z',
          fill: active ? 'currentColor' : 'none',
          stroke: 'currentColor',
          strokeWidth: 1.6,
          strokeLinejoin: 'round',
          opacity: active ? 1 : 0.75,
        }),
      )
    }

    function StatusDot(props) {
      return React.createElement('span', { className: 'am-dot ' + statusTone(props.status) })
    }

    function Card(props) {
      return React.createElement('div', { className: 'am-card' },
        React.createElement('div', { className: 'am-title' }, props.title),
        props.children,
      )
    }

    function Row(props) {
      return React.createElement('div', { className: 'am-row' },
        React.createElement('span', { className: 'am-label' }, props.label),
        props.children,
      )
    }

    function Switch(props) {
      return React.createElement('button', {
        type: 'button',
        className: 'am-switch' + (props.on ? ' on' : ''),
        'aria-pressed': !!props.on,
        title: props.title,
        onClick: props.onToggle,
        disabled: props.disabled,
      })
    }

    function Button(props) {
      return React.createElement('button', {
        type: 'button',
        className: 'am-button' + (props.primary ? ' primary' : ''),
        onClick: props.onClick,
        disabled: props.disabled,
      }, props.children)
    }

    function HistoryList(props) {
      var history = props.history
      if (!Array.isArray(history) || history.length === 0) {
        return React.createElement('div', { className: 'am-empty' }, '还没有操作记录')
      }
      return React.createElement('div', { className: 'am-history' },
        history.map(function (entry, index) {
          var kindLabel = entry.kind === 'pull' ? '拉取'
            : entry.kind === 'writeback' ? '写回'
            : entry.kind === 'config' ? '配置'
            : entry.kind === 'token' ? '令牌'
            : entry.kind === 'discover' ? '发现'
            : String(entry.kind || '记录')
          return React.createElement('div', { className: 'am-history-item', key: index },
            React.createElement('span', { className: 'am-history-time' }, formatTime(entry.at)),
            React.createElement('span', { className: 'am-history-kind' }, kindLabel),
            React.createElement(StatusDot, { status: statusTone(entry.status) }),
            React.createElement('span', null, entry.message || ''),
          )
        }),
      )
    }

    function MemoryPanel() {
      var statePair = React.useState(null)
      var status = statePair[0]
      var setStatus = statePair[1]
      var busyPair = React.useState(false)
      var busy = busyPair[0]
      var setBusy = busyPair[1]
      var noticePair = React.useState('')
      var notice = noticePair[0]
      var setNotice = noticePair[1]
      var draftPair = React.useState('')
      var draft = draftPair[0]
      var setDraft = draftPair[1]

      var refresh = function () {
        fetchStatus().then(setStatus, function (error) {
          setStatus({ ok: false, error: String((error && error.message) || error) })
        })
      }

      React.useEffect(function () {
        refresh()
        var timer = setInterval(refresh, 5000)
        return function () { clearInterval(timer) }
      }, [])

      var flash = function (text, tone) {
        amToast(text, tone)
        setNotice(text)
        setTimeout(function () { setNotice('') }, 4000)
      }

      var onPull = function () {
        if (busy) return
        setBusy(true)
        triggerPull().then(function (next) {
          setStatus(next)
          setBusy(false)
          flash(next && next.pullOk ? '拉取完成' : '拉取没有完全成功——多半是网络波动，稍后重试，已有记忆缓存不受影响 (´･ω･`)')
        }, function (error) {
          setBusy(false)
          flash('拉取失败：' + String((error && error.message) || error))
        })
      }

      var onSaveToken = function () {
        var value = String(draft || '').trim()
        if (!value) { flash('先粘贴令牌再点保存'); return }
        setBusy(true)
        saveToken(value).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setDraft('')
            if (result.verified) {
              flash('令牌已保存，仓库验证通过')
            } else {
              flash('令牌已保存，但仓库验证失败：' + (result.verifyMessage || '未知原因'))
            }
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
          setTimeout(refresh, 600)
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onToggleWriteback = function () {
        var current = !!(status && status.writebackEnabled)
        setBusy(true)
        updateConfig({ writebackEnabled: !current }).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash(!current ? '自动写回已开启' : '自动写回已关闭')
            setTimeout(refresh, 800)
          } else {
            flash('切换失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('切换失败：' + String((error && error.message) || error))
        })
      }

      if (status && status.ok === false) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement(Card, { title: 'Get记忆' },
            React.createElement('div', { className: 'am-notice' }, '无法读取插件状态：' + (status.error || '未知错误')),
          ),
        )
      }

      var token = (status && status.token) || { configured: false, source: null }
      var cache = status && status.cache
      var lastWriteback = status && status.lastWriteback

      return React.createElement('div', { className: 'am-panel' },
        React.createElement(GuideBanner),
        React.createElement(Card, { title: React.createElement(React.Fragment, null,
          React.createElement(AireIcon, { size: 16 }),
          'Get记忆 · ' + ((status && status.repo) || ''),
          status && status.ok ? React.createElement('span', { className: 'am-pulse', title: '插件在线' }) : null,
        ) },
          React.createElement(Row, { label: '记忆仓库' },
            React.createElement('span', { className: 'am-value' },
              status ? (status.repo + '@' + status.branch) : '…'),
          ),
          React.createElement(Row, { label: '最近拉取' },
            React.createElement('span', { className: 'am-value' },
              cache ? formatTime(cache.fetchedAt) + (cache.stale ? '（部分过期）' : '') : '尚未拉取'),
          ),
          React.createElement(Row, { label: '最近写回' },
            React.createElement('span', { className: 'am-value' },
              lastWriteback
                ? formatTime(lastWriteback.at) + ' · ' + (lastWriteback.phase === 'committed' ? '已提交' : lastWriteback.phase === 'skipped' ? '跳过' : lastWriteback.phase === 'error' ? '失败' : lastWriteback.phase)
                : '—'),
          ),
          React.createElement(Row, { label: '自动写回' },
            React.createElement(Switch, {
              on: !!status && !!status.writebackEnabled,
              onToggle: onToggleWriteback,
              disabled: busy || !status,
              title: '对话结束自动提取记忆写回仓库',
            }),
          ),
        ),

        React.createElement(Card, { title: '令牌' },
          React.createElement(Row, { label: '当前状态' },
            React.createElement('span', { className: 'am-value' },
              token.configured ? '已配置（' + tokenSourceLabel(token.source) + '）' : '未配置'),
          ),
          React.createElement('div', { className: 'am-row' },
            React.createElement('input', {
              className: 'am-input',
              type: 'password',
              placeholder: token.configured ? '留空保持不变，粘贴新令牌可替换' : '粘贴 GitHub 细颗粒度令牌（仅本仓库 Contents 读写）',
              value: draft,
              onChange: function (event) { setDraft(event.target.value) },
            }),
            React.createElement(Button, { primary: true, onClick: onSaveToken, disabled: busy }, '保存'),
          ),
          React.createElement('div', { className: 'am-notice' }, '令牌存入 DSH 凭据库，绝不写入记忆仓库'),
        ),

        React.createElement(Card, { title: '操作' },
          React.createElement(Row, { label: '立刻从仓库拉取最新记忆' },
            React.createElement(Button, { primary: true, onClick: onPull, disabled: busy }, busy ? '处理中…' : '立即拉取'),
          ),
          React.createElement(Row, { label: '完整配置' },
            React.createElement('span', { className: 'am-notice' }, '打开 DSH 设置 → 「Get记忆」页面，仓库、文件、防抖时长等全部字段都能在那里调整'),
          ),
        ),

        React.createElement(Card, { title: '最近修改记录' },
          React.createElement(HistoryList, { history: status && status.history }),
        ),

        notice
          ? React.createElement('div', { className: 'am-notice' }, notice)
          : null,
      )
    }

    // Layer: 设置引导——首次安装/大更新后在面板与设置页顶部显示引导卡（可叉，但至少点开一个教程后才能叉掉）。
    var GUIDE_STORAGE_KEY = 'dsh-get-memory:guide-seen'
    var GUIDE_VERSION = 'v0.5.1'

    // 弹窗用 portal 挂到 body：面板的毛玻璃滤镜会让 fixed 定位被圈在面板内，盖不住外面的保存浮层。
    var GuideReactDOM = null
    try { GuideReactDOM = require('react-dom') } catch { GuideReactDOM = null }

    var GUIDE_ITEMS = [
      {
        id: 'token',
        title: '前置：获取 GitHub 令牌',
        body: [
          '1. 前往 GitHub（代码托管网站）新建一个私有仓库（private repository），或挑一个已有的——它就是你的「记忆库」；',
          '2. 右上角头像 → Settings（设置）→ Developer settings（开发者设置）→ Personal access tokens（个人访问令牌）→ Fine-grained tokens（细颗粒度令牌）→ Generate new token（生成新令牌）；',
          '3. Repository access（仓库授权范围）选择 Only select repositories（只选择指定仓库），并勾选指定记忆库；Permissions（权限）里把 Contents（仓库内容）设为 Read and write（读写），其余权限一律不要；',
          '4. 生成后复制令牌（github_pat_ 开头），回到本插件粘贴保存。这个令牌能让所有装了本插件的前端读写同一份记忆。',
        ].join('\n\n'),
      },
      {
        id: 'setup',
        title: '新装配置引导',
        body: [
          '1. 令牌框粘贴令牌 → 保存；',
          '2. 「记忆仓库」会自动列出令牌能看到的仓库 → 选你的记忆库 → 保存全部设置；',
          '3. 读取到文件后可分别设置读写权限；空仓库可点击「一键初始化记忆仓库」，插件会帮你建好第一个文件；',
          '4. 回到对话界面正常聊天：自动把仓库内容注入上下文，新对话默认开启使用本插件。',
        ].join('\n\n'),
      },
      {
        id: 'custom',
        title: '快速自定义设置',
        body: [
          '· 记忆变动提醒胶囊：设置页「触发与范围」里开关，还能选「临时显示 / 长期显示」；',
          '· 仓库新文件默认「读写」（会作为写回目标），可在「文件权限」卡片里逐个改成「只读」；',
          '· 检查更新：设置页「其他」卡片点「检查更新」，检测到新版会提示更新；',
          '· 自动写回开关：默认关闭（保护模型额度），需要写入长期记忆时再打开。',
        ].join('\n\n'),
      },
      {
        id: 'tips',
        title: '使用 tips',
        body: [
          '【写回节奏】\n· 写回时机：一段对话结束并静止约 30 秒后，插件自动整理 0-2 分钟（调用模型 + 提交 GitHub），期间输入框下方会常驻「记忆整理中…」；',
          '【记忆仓库】\n· 底层逻辑：仓库里的 Markdown（纯文本标记格式）文件 = 你跨设备共享的记忆；GitHub 令牌 = 插件读写它们的钥匙；没配仓库之前插件不注入也不写回任何东西；\n· 本插件只适配 DSH（DeepSeek Harness 桌面应用）软件端。网页版 DSH 就是软件端的镜像页面，插件能力跟随软件端生效，不做独立 web 插件；',
          '【界面入口】\n· 每个对话窗口输入框下方都有「记忆 ✓/✕」小按钮，可以快捷暂停该窗口的写回；\n· 复制会话 ID：左侧会话列表点击「⋯」图标 →「复制会话 ID」，再粘进设置页「应用于会话」，就能精确圈定哪些窗口写回；\n· 改完任何设置记得点底部「保存全部设置」，否则不生效。',
        ].join('\n\n'),
      },
      {
        id: 'changelog',
        title: '本次重要更新（v0.5.0）',
        body: [
          '· 新增「设置引导」：首次使用手把手教学；',
          '· 输入框下方新增「本窗口记忆开关」，可单独暂停某个对话的写回；',
          '· 全局提示胶囊支持「长期显示 / 临时显示」两种模式；',
          '· 修复：仓库文件被删除后拉取会重复计「失败」，现在自动清理旧记录；',
          '· 文案更易读（「每多少条对话写回一次记忆」等）。',
        ].join('\n\n'),
      },
    ]

    function GuideModal(props) {
      if (!props.item) return null
      var modal = React.createElement('div', { className: 'am-guide-mask', onClick: props.onClose },
        React.createElement('div', { className: 'am-guide-modal', onClick: function (event) { event.stopPropagation() } },
          React.createElement('div', { className: 'am-guide-modal-head' },
            React.createElement('span', { className: 'am-guide-modal-title' }, props.item.title),
            React.createElement('button', { type: 'button', className: 'am-guide-close', onClick: props.onClose }, '×'),
          ),
          props.items
            ? React.createElement('div', { className: 'am-guide-banner-buttons' },
                props.items.map(function (item) {
                  return React.createElement('button', {
                    type: 'button',
                    className: 'am-guide-button' + (props.item.id === item.id ? ' am-guide-active' : ''),
                    key: item.id,
                    onClick: function () { if (props.onSelect) props.onSelect(item) },
                  }, item.title.replace(/^（.*?）/, '').split('：')[0].split('（')[0])
                }),
              )
            : null,
          React.createElement('div', { className: 'am-guide-modal-body' }, props.item.body),
        ),
      )
      if (GuideReactDOM && typeof GuideReactDOM.createPortal === 'function') {
        try { return GuideReactDOM.createPortal(modal, document.body) } catch { /* 回退内联渲染 */ }
      }
      return modal
    }

    function GuideBanner() {
      var seenPair = React.useState(function () {
        try { return localStorage.getItem(GUIDE_STORAGE_KEY) === GUIDE_VERSION } catch { return true }
      })
      var seen = seenPair[0]
      var setSeen = seenPair[1]
      var openedPair = React.useState(false)
      var openedAny = openedPair[0]
      var setOpenedAny = openedPair[1]
      var modalPair = React.useState(null)
      var modal = modalPair[0]
      var setModal = modalPair[1]

      var openItem = function (item) {
        setModal(item)
        if (!openedAny) {
          setOpenedAny(true)
          try { localStorage.setItem(GUIDE_STORAGE_KEY, GUIDE_VERSION) } catch { /* 忽略 */ }
        }
      }

      var dismiss = function () {
        if (!openedAny) return // 至少点开一个教程才能叉掉
        setSeen(true)
      }

      if (seen) return null
      return React.createElement(React.Fragment, null,
        React.createElement('div', { className: 'am-guide-banner' },
          React.createElement('div', { className: 'am-guide-banner-head' },
            React.createElement('span', { className: 'am-guide-banner-title' }, '💡 设置引导'),
            React.createElement('button', {
              type: 'button',
              className: 'am-guide-close' + (openedAny ? '' : ' am-disabled'),
              onClick: dismiss,
              title: openedAny ? '关闭引导' : '先点开一个教程看看，之后才能关闭',
            }, '×'),
          ),
          React.createElement('div', { className: 'am-guide-banner-buttons' },
            GUIDE_ITEMS.map(function (item) {
              return React.createElement('button', {
                type: 'button',
                className: 'am-guide-button',
                key: item.id,
                onClick: function () { openItem(item) },
              }, item.title.replace(/^（.*?）/, '').split('：')[0].split('（')[0])
            }),
          ),
          React.createElement('div', { className: 'am-notice' }, openedAny
            ? '教程看过了？点右上角 × 关闭。以后随时可在 设置 → 关于 Get记忆 → 「查看教程」回看。'
            : '第一次使用？从「获取 GitHub 令牌」开始，点开任意一个教程看完就能关闭本引导。以后随时可在 设置 → 关于 Get记忆 → 「查看教程」回看。'),
        ),
        React.createElement(GuideModal, { item: modal, onClose: function () { setModal(null) } }),
      )
    }

    // Layer: 教程入口——叉掉引导卡后，用户随时可以从「关于 Get记忆」卡片点开再看。
    function GuideLauncher(props) {
      var modalPair = React.useState(null)
      var modal = modalPair[0]
      var setModal = modalPair[1]

      return React.createElement(React.Fragment, null,
        React.createElement(Button, { onClick: function () { setModal(GUIDE_ITEMS[0]) } }, '查看教程'),
        React.createElement(GuideModal, {
          item: modal,
          items: GUIDE_ITEMS,
          onSelect: function (item) { setModal(item) },
          onClose: function () { setModal(null) },
        }),
      )
    }

    // Layer: 顶部提醒气泡（toast）——所有操作反馈统一走这里，浮在界面最上方，几秒自动消失。
    var toastListeners = []
    var toastSeq = 0

    function amToast(text, tone) {
      toastSeq += 1
      var entry = { id: toastSeq, text: String(text), tone: tone || 'warn' }
      toastListeners.forEach(function (fn) { try { fn(entry) } catch { /* 忽略 */ } })
    }

    function subscribeToast(fn) {
      toastListeners.push(fn)
      return function () {
        toastListeners = toastListeners.filter(function (item) { return item !== fn })
      }
    }

    function ToastHost() {
      var listPair = React.useState([])
      var list = listPair[0]
      var setList = listPair[1]
      var timersRef = React.useRef({})

      React.useEffect(function () {
        var alive = true
        var off = subscribeToast(function (entry) {
          if (!alive) return
          setList(function (current) {
            return current.concat([entry]).slice(-3)
          })
          var t = setTimeout(function () {
            if (!alive) return
            setList(function (current) { return current.filter(function (item) { return item.id !== entry.id }) })
          }, entry.text.length > 40 ? 6500 : 4500)
          timersRef.current[entry.id] = t
        })
        return function () {
          alive = false
          off()
          Object.keys(timersRef.current).forEach(function (key) { clearTimeout(timersRef.current[key]) })
        }
      }, [])

      return React.createElement('div', { className: 'am-toast-root' },
        list.map(function (entry) {
          return React.createElement('div', { className: 'am-toast ' + entry.tone, key: entry.id }, entry.text)
        }),
      )
    }

    // Layer: 每回合结束处的记忆写回指示（conversation.chat.turnTail）。
    var INDICATOR_TIMEOUT_MS = 180000
    var INDICATOR_POLL_MS = 3000

    function fetchWriteback(sessionId, turn, seq) {
      var params = new URLSearchParams()
      params.set('session', String(sessionId === undefined || sessionId === null ? '' : sessionId))
      if (turn !== undefined && turn !== null) params.set('turn', String(turn))
      if (seq !== undefined && seq !== null) params.set('seq', String(seq))
      return fetchJson(WRITEBACK_URL + '?' + params.toString())
    }

    function TurnMemoryIndicator(props) {
      var sessionId = props && props.sessionId
      var turnProp = props && props.turn
      var turn = (typeof turnProp === 'object' && turnProp !== null) ? turnProp.turn : turnProp
      var seq = props && props.seq

      var recordPair = React.useState(null)
      var record = recordPair[0]
      var setRecord = recordPair[1]
      var livePair = React.useState(true)
      var live = livePair[0]
      var setLive = livePair[1]

      React.useEffect(function () {
        var stop = false
        var settled = false
        var started = Date.now()

        var check = function () {
          if (stop) return
          fetchWriteback(sessionId, turn, seq).then(function (data) {
            if (stop) return
            if (data && data.found === true && data.record) {
              setRecord(data.record)
              if (data.record.phase === 'committed' || data.record.phase === 'skipped' || data.record.phase === 'error') {
                settled = true
              }
            } else if (Date.now() - started > INDICATOR_TIMEOUT_MS) {
              setLive(false)
            }
          }, function () {
            if (Date.now() - started > INDICATOR_TIMEOUT_MS) setLive(false)
          })
        }

        check()
        var timer = setInterval(function () {
          if (stop || settled) return
          if (Date.now() - started > INDICATOR_TIMEOUT_MS) { setLive(false); return }
          check()
        }, INDICATOR_POLL_MS)

        return function () {
          stop = true
          clearInterval(timer)
        }
      }, [sessionId, turn, seq])

      if (!live || !record) return null

      var text = null
      var tone = null
      if (record.phase === 'attempt') { text = '记忆整理中…'; tone = 'warn' }
      else if (record.phase === 'committed') { text = '记忆已写回 ✓'; tone = 'ok' }
      else if (record.phase === 'skipped') { text = '无新记忆'; tone = 'skip' }
      else if (record.phase === 'error') { text = '记忆写回失败'; tone = 'error' }
      if (text === null) return null

      var detail = record.summary || record.message || ''
      return React.createElement('div', {
        className: 'am-indicator',
        title: detail,
      },
        React.createElement(StatusDot, { status: tone }),
        React.createElement('span', null, 'Get记忆 · ' + text),
      )
    }

    // Layer: 原生设置页里的完整配置页面（settings.section）。
    function FieldRow(props) {
      return React.createElement('div', { className: 'am-row' },
        React.createElement('span', { className: 'am-label' }, props.label),
        props.children,
      )
    }

    function TextField(props) {
      return React.createElement('input', {
        className: 'am-input',
        type: props.type || 'text',
        value: props.value === undefined || props.value === null ? '' : String(props.value),
        placeholder: props.placeholder || '',
        onChange: function (event) { props.onChange(event.target.value) },
      })
    }

    function TextAreaField(props) {
      return React.createElement('textarea', {
        className: 'am-input am-textarea',
        rows: 3,
        value: props.value === undefined || props.value === null ? '' : String(props.value),
        placeholder: props.placeholder || '',
        onChange: function (event) { props.onChange(event.target.value) },
      })
    }

    function NumberField(props) {
      var min = props.min === undefined ? 1 : props.min
      var current = Number(props.value)
      var clamped = Number.isFinite(current) ? Math.max(min, Math.floor(current)) : min
      return React.createElement('div', { className: 'am-number-field' },
        React.createElement('button', {
          type: 'button',
          className: 'am-number-btn',
          disabled: clamped <= min,
          title: clamped <= min ? '最小就是 ' + min : '',
          onClick: function () { props.onChange(Math.max(min, clamped - 1)) },
        }, '−'),
        React.createElement('input', {
          className: 'am-input am-number-input',
          type: 'number',
          min: min,
          step: 1,
          value: props.value === undefined || props.value === null ? '' : String(props.value),
          onChange: function (event) {
            var raw = event.target.value
            var num = Number(raw)
            if (raw === '' || !Number.isFinite(num) || num < min) {
              // 输入非法时先不写回，失焦时 NumberField 的 value 仍受控；直接夹到最小
              if (raw === '') return
              props.onChange(min)
              return
            }
            props.onChange(Math.floor(num))
          },
          onBlur: function (event) {
            var num = Number(event.target.value)
            if (!Number.isFinite(num) || num < min) props.onChange(min)
          },
        }),
        React.createElement('button', {
          type: 'button',
          className: 'am-number-btn',
          onClick: function () { props.onChange(clamped + 1) },
        }, '+'),
      )
    }

    function SettingsPage() {
      var statePair = React.useState(null)
      var status = statePair[0]
      var setStatus = statePair[1]
      var busyPair = React.useState(false)
      var busy = busyPair[0]
      var setBusy = busyPair[1]
      var noticePair = React.useState('')
      var notice = noticePair[0]
      var setNotice = noticePair[1]

      var formPair = React.useState(null)
      var form = formPair[0]
      var setForm = formPair[1]
      var tokenDraftPair = React.useState('')
      var tokenDraft = tokenDraftPair[0]
      var setTokenDraft = tokenDraftPair[1]
      var repoListPair = React.useState(null) // { ok, count, repos: [{full_name, private}] } | null
      var repoList = repoListPair[0]
      var setRepoList = repoListPair[1]
      var latestVersionPair = React.useState(null)
      var latestVersion = latestVersionPair[0]
      var setLatestVersion = latestVersionPair[1]

      var loadRepos = function (silent) {
        fetchRepos().then(function (result) {
          setRepoList(result && result.ok ? result : { ok: false, error: (result && result.error) || '未知错误', repos: [] })
          if (!silent && result && !result.ok) flash('获取仓库列表失败：' + (result.error || '未知错误'))
        }, function (error) {
          setRepoList({ ok: false, error: String((error && error.message) || error), repos: [] })
          if (!silent) flash('获取仓库列表失败：' + String((error && error.message) || error))
        })
      }

      React.useEffect(function () {
        loadRepos(true)
      }, [])

      // 表单脏标记：只要用户动过任何字段，轮询就不再拿服务器值覆盖草稿
      var formRef = React.useRef(null)

      var refresh = function () {
        fetchStatus().then(function (next) {
          setStatus(next)
          if (next && next.settings && formRef.current === null) {
            var f = cloneForm(next.settings)
            formRef.current = f
            setForm(f)
          }
        }, function (error) {
          setStatus({ ok: false, error: String((error && error.message) || error) })
        })
      }

      React.useEffect(function () {
        refresh()
        var timer = setInterval(refresh, 8000)
        return function () { clearInterval(timer) }
      }, [])

      var flash = function (text, tone) {
        amToast(text, tone)
        setNotice(text)
        setTimeout(function () { setNotice('') }, 5000)
      }

      var setField = function (key, value) {
        setForm(function (current) {
          var next = Object.assign({}, current || {})
          next[key] = value
          formRef.current = next
          return next
        })
      }

      // ---- 文件权限中心 ----
      var fileSyncPair = React.useState(null)
      var fileSync = fileSyncPair[0]
      var setFileSync = fileSyncPair[1]

      var onSyncFiles = function () {
        if (busy) return
        setBusy(true)
        syncFiles().then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setFileSync({ files: result.files, removed: result.removed })
            flash('文件列表已同步（' + (result.files ? result.files.length : 0) + ' 个文件）')
          } else {
            flash('同步失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('同步失败：' + String((error && error.message) || error))
        })
      }

      var onToggleFileMode = function (file) {
        setFileSync(function (current) {
          if (!current) return current
          var files = (current.files || []).map(function (entry) {
            if (entry.file !== file) return entry
            return Object.assign({}, entry, { mode: entry.mode === 'rw' ? 'ro' : 'rw' })
          })
          return { files: files, removed: current.removed }
        })
      }

      var onApplyFileModes = function () {
        if (!fileSync) return
        setBusy(true)
        var modes = (fileSync.files || []).map(function (entry) { return { file: entry.file, mode: entry.mode } })
        saveFileModes(modes).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash('文件权限已应用（' + (result.applied || 0) + ' 个）')
            setTimeout(refresh, 600)
          } else {
            flash('应用失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('应用失败：' + String((error && error.message) || error))
        })
      }

      var onInitRepo = function () {
        if (busy) return
        setBusy(true)
        initRepo().then(function (result) {
          setBusy(false)
          if (result && result.ok && result.initOk) {
            flash('初始化成功！已创建 ' + result.created + '，开始使用吧')
            onSyncFiles()
            setTimeout(refresh, 600)
          } else {
            flash((result && result.message) || '初始化失败')
          }
        }, function (error) {
          setBusy(false)
          flash('初始化失败：' + String((error && error.message) || error))
        })
      }

      var onCheckUpdate = function () {
        if (busy) return
        setBusy(true)
        checkUpdate().then(function (meta) {
          setBusy(false)
          setLatestVersion(meta && meta.version ? meta.version : null)
          var current = status && status.version ? status.version : '未知'
          if (meta && meta.version && meta.version !== current) {
            flash('发现新版本 ' + meta.version + '（当前 ' + current + '）。更新命令：dsh plugin --profile web add dsh-get-memory@' + meta.version)
          } else if (meta && meta.version) {
            flash('已是最新版本 ' + meta.version)
          } else {
            flash('检查失败：没拿到版本信息')
          }
        }, function (error) {
          setBusy(false)
          flash('检查更新失败：' + String((error && error.message) || error))
        })
      }

      var onSave = function () {
        if (!form) return
        setBusy(true)
        var patch = {}
        patch.repo = String(form.repo || '').trim()
        patch.branch = String(form.branch || '').trim()
        patch.ledgerFile = String(form.ledgerFile || '').trim()
        patch.injectOrder = Number(form.injectOrder)
        patch.writebackEnabled = !!form.writebackEnabled
        patch.writebackDebounceMs = Number(form.writebackDebounceMs)
        patch.maxTranscriptChars = Number(form.maxTranscriptChars)
        patch.minConversationChars = Number(form.minConversationChars)
        patch.extractProvider = String(form.extractProvider || '').trim()
        patch.extractModel = String(form.extractModel || '').trim()
        patch.requestTimeoutMs = Number(form.requestTimeoutMs)
        patch.historyLimit = Number(form.historyLimit)
        patch.autoDiscoverFiles = !!form.autoDiscoverFiles
        patch.writebackEveryN = Math.max(1, Number(form.writebackEveryN) || 5)
        patch.sessionPolicyMode = form.sessionPolicyMode === 'exclude' || form.sessionPolicyMode === 'include' ? form.sessionPolicyMode : 'all'
        patch.sessionPolicyIds = String(form.sessionPolicyIds || '')
          .split('\n').map(function (line) { return line.trim() }).filter(Boolean)
        patch.showGlobalNotice = !!form.showGlobalNotice
        patch.showGlobalNoticeMode = form.showGlobalNoticeMode === 'persistent' ? 'persistent' : 'momentary'
        patch.sessionsEnabledByDefault = !!form.sessionsEnabledByDefault
        patch.maxWriteFiles = Math.max(1, Number(form.maxWriteFiles) || 5)
        updateConfig(patch).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash('设置已保存并生效')
            setTimeout(refresh, 600)
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onSaveToken = function () {
        var value = String(tokenDraft || '').trim()
        if (!value) { flash('先粘贴令牌再点保存'); return }
        setBusy(true)
        saveToken(value).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setTokenDraft('')
            flash(result.verified ? '令牌已保存，仓库验证通过' : '令牌已保存，正在读取仓库列表…')
            loadRepos()
            setTimeout(refresh, 600)
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onPull = function () {
        if (busy) return
        setBusy(true)
        triggerPull().then(function (next) {
          setBusy(false)
          setStatus(next)
          flash(next && next.pullOk ? '拉取完成' : '拉取没有完全成功——多半是网络波动，稍后重试，已有记忆缓存不受影响 (´･ω･`)')
        }, function (error) {
          setBusy(false)
          flash('拉取失败：' + String((error && error.message) || error))
        })
      }

      if (!status) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement('div', { className: 'am-notice' }, '读取插件状态中…'),
        )
      }

      if (status.ok === false) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement('div', { className: 'am-notice' }, '无法读取插件状态：' + (status.error || '未知错误')),
        )
      }

      var token = status.token || { configured: false, source: null }
      var cache = status.cache
      var lastWriteback = status.lastWriteback

      return React.createElement('div', { className: 'am-panel am-settings' },
        React.createElement(GuideBanner),
        React.createElement(Card, { title: '状态' },
          React.createElement(Row, { label: '最近拉取' },
            React.createElement('span', { className: 'am-value' },
              cache ? formatTime(cache.fetchedAt) + (cache.stale ? '（部分过期）' : '') : '尚未拉取'),
          ),
          React.createElement(Row, { label: '最近写回' },
            React.createElement('span', { className: 'am-value' },
              lastWriteback
                ? formatTime(lastWriteback.at) + ' · ' + (lastWriteback.phase === 'committed' ? '已提交' : lastWriteback.phase === 'skipped' ? '跳过' : lastWriteback.phase === 'error' ? '失败' : lastWriteback.phase)
                : '—'),
          ),
          React.createElement(Row, { label: '操作' },
            React.createElement(Button, { primary: true, onClick: onPull, disabled: busy }, busy ? '处理中…' : '立即拉取'),
          ),
        ),

        React.createElement(Card, { title: '令牌' },
          React.createElement(Row, { label: '当前状态' },
            React.createElement('span', { className: 'am-value' },
              token.configured ? '已配置（' + tokenSourceLabel(token.source) + '）' : '未配置'),
          ),
          React.createElement('div', { className: 'am-row' },
            React.createElement('input', {
              className: 'am-input',
              type: 'password',
              placeholder: token.configured ? '留空保持不变，粘贴新令牌可替换' : '粘贴 GitHub 细颗粒度令牌（仅目标仓库 Contents 读写）',
              value: tokenDraft,
              onChange: function (event) { setTokenDraft(event.target.value) },
            }),
            React.createElement(Button, { primary: true, onClick: onSaveToken, disabled: busy }, '保存'),
          ),
          React.createElement('div', { className: 'am-notice' }, '令牌存入 DSH 凭据库，绝不写入记忆仓库'),
        ),

        React.createElement(Card, { title: '记忆仓库' },
          React.createElement(FieldRow, { label: '选择仓库' },
            React.createElement('select', {
              className: 'am-input',
              value: form ? form.repo : '',
              disabled: busy || !repoList,
              onChange: function (event) { setField('repo', event.target.value) },
            },
              React.createElement('option', { value: '' }, form && form.repo ? form.repo + '（当前）' : '— 选择一个仓库 —'),
              (repoList && repoList.repos ? repoList.repos : []).map(function (entry) {
                return React.createElement('option', { value: entry.full_name, key: entry.full_name },
                  entry.full_name + (entry.private ? '（私有）' : ''))
              }),
            ),
          ),
          React.createElement('div', { className: 'am-row' },
            React.createElement(Button, { onClick: function () { loadRepos(false) }, disabled: busy }, '刷新仓库列表'),
          ),
          React.createElement('div', { className: 'am-notice' },
            '仓库列表来自你保存的令牌：列表里出现的仓库才可读写。看不到目标仓库？去 GitHub 把令牌授权加到这个仓库上，再回来刷新。'),
          form && form.repo
            ? null
            : React.createElement('div', { className: 'am-notice' }, '还没选仓库：现在不会注入任何内容，也不会写回。'),
        ),

        React.createElement(Card, { title: '文件权限' },
          React.createElement(Row, { label: '同步仓库文件列表' },
            React.createElement(Button, { primary: true, onClick: onSyncFiles, disabled: busy }, busy ? '同步中…' : '同步文件列表'),
          ),
          fileSync && fileSync.files && fileSync.files.length === 0
            ? React.createElement('div', { className: 'am-row' },
                React.createElement(Button, { primary: true, onClick: onInitRepo, disabled: busy }, busy ? '初始化中…' : '一键初始化记忆仓库'),
              )
            : null,
          fileSync && fileSync.files && fileSync.files.length === 0
            ? React.createElement('div', { className: 'am-notice' },
                '这个仓库还没有记忆文件。点「一键初始化」，插件会用你的令牌自动创建一个 长期记忆账本.md，之后就能正常读写——不用你去 GitHub 手动建。')
            : null,
          fileSync && fileSync.files
            ? fileSync.files.map(function (entry) {
                return React.createElement(Row, { label: React.createElement(React.Fragment, null,
                  entry.file,
                  entry.isNew ? React.createElement('span', { className: 'am-notice', key: 'n' }, '（新）') : null,
                ) },
                  React.createElement('div', { className: 'am-row' },
                    React.createElement(Button, {
                      primary: entry.mode === 'rw',
                      onClick: function () { if (entry.mode !== 'rw') onToggleFileMode(entry.file) },
                    }, '读写'),
                    React.createElement(Button, {
                      primary: entry.mode === 'ro',
                      onClick: function () { if (entry.mode !== 'ro') onToggleFileMode(entry.file) },
                    }, '只读'),
                  ),
                )
              })
            : React.createElement('div', { className: 'am-empty' }, '点「同步文件列表」拉取仓库当前文件'),
          fileSync && fileSync.removed && fileSync.removed.length > 0
            ? React.createElement('div', { className: 'am-notice' }, '已删除（将从权限表移除）：' + fileSync.removed.join('、'))
            : null,
          fileSync && fileSync.files && fileSync.files.length > 0
            ? React.createElement(Row, { label: '应用以上权限' },
                React.createElement(Button, { primary: true, onClick: onApplyFileModes, disabled: busy }, '应用'),
              )
            : null,
          React.createElement('div', { className: 'am-notice' }, '「只读」仅注入上下文；「读写」在对话结束后也会作为写回目标（新文件默认读写）'),
        ),

        React.createElement(Card, { title: '写回与提取' },
          React.createElement(Row, { label: '自动写回' },
            React.createElement(Switch, {
              on: form ? !!form.writebackEnabled : false,
              onToggle: function () { setField('writebackEnabled', !(form && form.writebackEnabled)) },
              disabled: busy,
              title: '对话结束后自动提取新记忆并写回仓库（会消耗模型额度，默认关闭）',
            }),
          ),
          React.createElement('div', { className: 'am-notice' }, '开启后：回合结束并静止约 30 秒后开始写回；等待期内发送新消息会顺延。写回需调用模型并提交到仓库，通常耗时 1-3 分钟，期间输入框下方会常驻「记忆整理中…」提示。'),
        ),

        React.createElement(Card, { title: '触发与范围' },
          React.createElement(FieldRow, { label: '每多少条对话写回一次记忆' },
            React.createElement(NumberField, { value: form ? form.writebackEveryN : 5, onChange: function (v) { setField('writebackEveryN', v) } }),
          ),
          React.createElement('div', { className: 'am-notice' }, '填 1 = 每条对话结束后都写回；填 5 = 攒够 5 条才写一次。数字越大越省模型额度。'),
          React.createElement(FieldRow, { label: '应用于会话' },
            React.createElement('select', {
              className: 'am-input',
              value: form ? form.sessionPolicyMode : 'all',
              onChange: function (event) { setField('sessionPolicyMode', event.target.value) },
            },
              React.createElement('option', { value: 'all' }, '全部会话'),
              React.createElement('option', { value: 'exclude' }, '排除以下会话'),
              React.createElement('option', { value: 'include' }, '仅以下会话'),
            ),
          ),
          form && form.sessionPolicyMode !== 'all'
            ? React.createElement(React.Fragment, null,
                React.createElement(FieldRow, { label: '会话 ID（每行一个）' },
                  React.createElement(TextAreaField, {
                    value: form.sessionPolicyIds,
                    placeholder: '粘贴会话 ID，每行一个',
                    onChange: function (v) { setField('sessionPolicyIds', v) },
                  }),
                ),
                React.createElement('div', { className: 'am-notice' }, '会话 ID 是每个对话窗口的「门牌号」。去左侧会话列表，点那一行的「⋯」→「复制会话 ID」，回来粘贴即可；只填一段也能模糊匹配。'),
              )
            : null,
          React.createElement(Row, { label: '写回变动全局提示' },
            React.createElement(Switch, {
              on: form ? form.showGlobalNotice !== false : true,
              onToggle: function () { setField('showGlobalNotice', form ? form.showGlobalNotice === false : false) },
              disabled: busy,
              title: '输入框下方全程提示：整理中（常驻）→ 已更新 / 无新记忆 / 失败',
            }),
          ),
          React.createElement(FieldRow, { label: '胶囊显示方式' },
            React.createElement('select', {
              className: 'am-input',
              value: form ? (form.showGlobalNoticeMode === 'momentary' ? 'momentary' : 'persistent') : 'persistent',
              onChange: function (event) { setField('showGlobalNoticeMode', event.target.value) },
            },
              React.createElement('option', { value: 'momentary' }, '仅变动后临时显示'),
              React.createElement('option', { value: 'persistent' }, '长期显示最近状态'),
            ),
          ),
          React.createElement('div', { className: 'am-notice' }, '临时 = 弹几秒就消失；长期 = 「记忆已更新 / 无新记忆」小胶囊一直挂到下次变化。'),
          React.createElement(Row, { label: '新建对话默认使用 Get记忆' },
            React.createElement(Switch, {
              on: form ? form.sessionsEnabledByDefault !== false : true,
              onToggle: function () { setField('sessionsEnabledByDefault', form ? form.sessionsEnabledByDefault === false : false) },
              disabled: busy,
              title: '关闭后，新建对话默认暂停写回（每个窗口输入框下方可单独再开）',
            }),
          ),
        ),

        React.createElement(Card, { title: '其他' },
          React.createElement(Row, { label: '自动发现新文件' },
            React.createElement(Switch, {
              on: form ? form.autoDiscoverFiles !== false : true,
              onToggle: function () { setField('autoDiscoverFiles', form ? form.autoDiscoverFiles === false : false) },
              disabled: busy,
              title: '每次拉取时把仓库根目录新出现的 .md 文件自动加入注入列表',
            }),
          ),
          React.createElement(Row, { label: '版本' },
            React.createElement('span', { className: 'am-value' },
              '当前 ' + (status && status.version ? status.version : '未知')
              + (latestVersion ? '　·　npm 最新 ' + latestVersion : ''),
            ),
          ),
          React.createElement(Row, { label: '检查更新' },
            React.createElement(Button, { onClick: onCheckUpdate, disabled: busy }, busy ? '检查中…' : '检查更新'),
          ),
          React.createElement('div', { className: 'am-notice' }, '更新方式：`dsh plugin --profile web add dsh-get-memory@最新版本号`'),
        ),

        React.createElement(Card, { title: '关于 Get记忆' },
          React.createElement('div', { className: 'am-row' },
            React.createElement('a', { className: 'am-link', href: 'https://github.com/krodon998/dsh-get-memory', target: '_blank', rel: 'noreferrer' }, 'GitHub 仓库'),
            React.createElement('a', { className: 'am-link', href: 'https://github.com/krodon998/dsh-get-memory/issues', target: '_blank', rel: 'noreferrer' }, '问题反馈'),
            React.createElement(GuideLauncher),
          ),
          React.createElement('details', { className: 'am-changelog' },
            React.createElement('summary', null, '更新记录'),
            React.createElement('div', { className: 'am-changelog-body' }, [
              ['v0.5.0', '设置引导、本窗口记忆开关、胶囊常显/临时模式、拉取404自动清理、文案易读化'],
              ['v0.4.2', '注入绑定声明（代入感兜底）'],
              ['v0.4.1', '一键初始化空仓库、设置页检查更新'],
              ['v0.4.0', '令牌驱动仓库选择器、安全默认（空仓库不注入、写回默认关）'],
              ['v0.3.x', '文件权限中心、多文件写回、触发与范围、全局提示胶囊'],
            ].map(function (entry) {
              return React.createElement('div', { className: 'am-changelog-row', key: entry[0] },
                React.createElement('span', { className: 'am-changelog-ver' }, entry[0]),
                React.createElement('span', null, entry[1]),
              )
            })),
          ),
        ),

        React.createElement('div', { className: 'am-save-bar' },
          React.createElement('span', { className: 'am-save-hint' }, '有改动记得保存，否则不生效'),
          React.createElement(Button, { primary: true, onClick: onSave, disabled: busy || !form }, busy ? '保存中…' : '保存全部设置'),
        ),
        notice ? React.createElement('div', { className: 'am-notice' }, notice) : null,
      )
    }

    function cloneForm(settings) {
      return {
        repo: settings.repo,
        branch: settings.branch,
        ledgerFile: settings.ledgerFile,
        injectOrder: settings.injectOrder,
        writebackEnabled: settings.writebackEnabled,
        writebackDebounceMs: settings.writebackDebounceMs,
        maxTranscriptChars: settings.maxTranscriptChars,
        minConversationChars: settings.minConversationChars,
        extractProvider: settings.extractProvider,
        extractModel: settings.extractModel,
        requestTimeoutMs: settings.requestTimeoutMs,
        historyLimit: settings.historyLimit,
        autoDiscoverFiles: settings.autoDiscoverFiles,
        writebackEveryN: settings.writebackEveryN,
        sessionPolicyMode: settings.sessionPolicyMode,
        sessionPolicyIds: Array.isArray(settings.sessionPolicyIds) ? settings.sessionPolicyIds.join('\n') : '',
        showGlobalNotice: settings.showGlobalNotice,
        showGlobalNoticeMode: settings.showGlobalNoticeMode === 'momentary' ? 'momentary' : 'persistent',
        sessionsEnabledByDefault: settings.sessionsEnabledByDefault,
        maxWriteFiles: settings.maxWriteFiles,
      }
    }

    // Layer: 全局提示——写回全程可见：进行中常驻「记忆整理中…」，成功后按模式显示「记忆已更新」。
    // showGlobalNoticeMode: 'momentary' = 变动后临时显示几秒；'persistent' = 常驻显示最近状态直到下次变化。
    function GlobalMemoryNotice() {
      var statePair = React.useState(null) // { kind: 'progress' | 'done' | 'error' | 'skip', text: string }
      var state = statePair[0]
      var setState = statePair[1]
      var lastSeenPair = React.useRef(null)
      var modeRef = React.useRef('momentary')

      React.useEffect(function () {
        var alive = true
        var hideTimer = null
        var scheduleHide = function (ms) {
          if (modeRef.current === 'persistent') return // 常显模式：不自动消失
          if (hideTimer) clearTimeout(hideTimer)
          hideTimer = setTimeout(function () { if (alive) setState(null) }, ms)
        }
        var poll = function () {
          fetchStatus().then(function (status) {
            if (!alive || !status || status.ok === false) return
            if (status.settings && status.settings.showGlobalNotice === false) {
              setState(null)
              return
            }
            modeRef.current = status.settings && status.settings.showGlobalNoticeMode === 'persistent' ? 'persistent' : 'momentary'
            var wb = status.lastWriteback
            if (!wb || !wb.phase) {
              setState(null)
              return
            }
            if (wb.phase === 'attempt') {
              if (hideTimer) clearTimeout(hideTimer)
              setState({ kind: 'progress', text: '记忆整理中…' })
              return
            }
            if (wb.phase === 'committed' && wb.at) {
              if (lastSeenPair.current !== wb.at) {
                lastSeenPair.current = wb.at
                setState({ kind: 'done', text: wb.summary || '记忆已更新' })
                scheduleHide(12000)
              }
              return
            }
            if (wb.phase === 'error') {
              if (lastSeenPair.current !== 'err:' + wb.at) {
                lastSeenPair.current = 'err:' + wb.at
                setState({ kind: 'error', text: '记忆写回失败' })
                scheduleHide(8000)
              }
              return
            }
            if (wb.phase === 'skipped' && wb.at) {
              if (lastSeenPair.current !== 'skip:' + wb.at) {
                lastSeenPair.current = 'skip:' + wb.at
                var skipText = wb.reason === 'transcript-too-short' ? '对话太短，已跳过'
                  : wb.reason === 'every-n' ? '本轮跳过（每 ' + (status.settings && status.settings.writebackEveryN ? status.settings.writebackEveryN : 5) + ' 条对话写回一次）'
                  : '无新记忆'
                setState({ kind: 'skip', text: skipText })
                scheduleHide(8000)
              }
              return
            }
            setState(null)
          }, function () { /* 网络抖动忽略 */ })
        }
        poll()
        var interval = setInterval(poll, 3000)
        return function () {
          alive = false
          clearInterval(interval)
          if (hideTimer) clearTimeout(hideTimer)
        }
      }, [])

      if (!state) return null
      var tone = state.kind === 'done' ? 'ok' : state.kind === 'error' ? 'error' : state.kind === 'skip' ? 'skip' : 'warn'
      var className = 'am-global-notice'
      if (state.kind === 'progress') className += ' am-notice-progress'
      var dot = state.kind === 'progress'
        ? React.createElement('span', { className: 'am-pulse-dot' })
        : React.createElement(StatusDot, { status: tone })
      return React.createElement('div', { className: className, role: 'status' },
        dot,
        React.createElement('span', null, state.text),
      )
    }

    // Layer: 输入框下方 Dock——本窗口开关 + 全局提示胶囊。
    function DockMemoryControl(props) {
      var session = props && props.sessionId ? String(props.sessionId) : ''
      var enabledPair = React.useState(null)
      var enabled = enabledPair[0]
      var setEnabled = enabledPair[1]

      React.useEffect(function () {
        var alive = true
        fetchSessionEnabled(session).then(function (result) {
          if (alive && result && result.ok) setEnabled(!!result.enabled)
        }, function () { /* 忽略 */ })
        return function () { alive = false }
      }, [session])

      var toggle = function () {
        var next = !enabled
        setEnabled(next)
        setSessionEnabled(session, next).then(function (result) {
          if (result && result.ok) setEnabled(!!result.enabled)
        }, function () { /* 失败恢复原样 */
          fetchSessionEnabled(session).then(function (r) { if (r && r.ok) setEnabled(!!r.enabled) })
        })
      }

      return React.createElement('div', { className: 'am-dock-control' },
        React.createElement('div', { className: 'am-dock-pill' },
          React.createElement('button', {
            type: 'button',
            className: 'am-session-toggle' + (enabled ? ' am-on' : ''),
            onClick: toggle,
            title: enabled ? '本窗口正在使用 Get记忆（点击关闭写回）' : '本窗口已暂停写回记忆（点击开启）',
          }, '记忆' + (enabled === null ? '' : enabled ? ' ✓' : ' ✕')),
          React.createElement(GlobalMemoryNotice),
        ),
      )
    }

    // Layer: mount the right-rail icon, the main panel, the Plugins-page row config page, and package styles; all reversible.
    var name = 'dsh-aire-memory'
    var inject = ['slots']

    // 顶部提醒气泡：挂到 body 上（全局唯一），操作反馈统一从这里弹出。
    var ToastReactDOM = null
    try { ToastReactDOM = require('react-dom') } catch { ToastReactDOM = null }
    var toastRootEl = null
    function mountToastHost() {
      if (toastRootEl && document.body && document.body.contains(toastRootEl)) return
      try {
        toastRootEl = document.createElement('div')
        toastRootEl.id = 'am-toast-root'
        document.body.appendChild(toastRootEl)
        if (ToastReactDOM && typeof ToastReactDOM.createRoot === 'function') {
          ToastReactDOM.createRoot(toastRootEl).render(React.createElement(ToastHost))
        } else if (ToastReactDOM && typeof ToastReactDOM.render === 'function') {
          ToastReactDOM.render(React.createElement(ToastHost), toastRootEl)
        }
      } catch { toastRootEl = null }
    }

    function apply(ctx, config) {
      var slots = ctx.get('slots')
      if (slots === undefined || React === undefined) return

      ctx.effect(installStyles, 'aire-memory: styles')
      ctx.effect(mountToastHost, 'aire-memory: toast host')

      // 全局提示 + 本窗口开关：输入框下方（conversation.composer.dock）
      ctx.effect(function () {
        return slots.inject('conversation.composer.dock', function () {
          return slots.register(
            { name: 'conversation.composer.dock', id: 'aire-memory-notice', order: 20, label: 'Get记忆' },
            function AireDockControl(props) {
              return React.createElement(DockMemoryControl, props)
            },
          )
        })
      }, 'aire-memory: global notice')

      // 会话列表「⋯」菜单：复制会话 ID（配合设置页「应用于会话」）
      ctx.effect(function () {
        return slots.inject('sidebar.workspaces.session.menu.item', function () {
          return slots.register(
            { name: 'sidebar.workspaces.session.menu.item', id: 'dsh-get-memory-copy-session-id', order: 450 },
            function CopySessionIdMenuItem(props) {
              var useMenuOpenState = props && typeof props.useMenuOpenState === 'function' ? props.useMenuOpenState : null
              var setMenuOpen = useMenuOpenState ? useMenuOpenState()[1] : null
              var onSelect = function () {
                if (setMenuOpen) setMenuOpen(false)
                var id = String((props && props.sessionId) || '')
                var toast = function () { amToast(id ? '已复制会话 ID：' + id : '这个会话暂时没有 ID') }
                try {
                  if (navigator.clipboard && navigator.clipboard.writeText) {
                    navigator.clipboard.writeText(id).then(toast, function () {
                      try { window.prompt('复制下面这串会话 ID：', id) } catch { /* 忽略 */ }
                      toast()
                    })
                  } else {
                    try { window.prompt('复制下面这串会话 ID：', id) } catch { /* 忽略 */ }
                    toast()
                  }
                } catch { toast() }
              }
              return React.createElement('button', {
                type: 'button',
                role: 'menuitem',
                className: 'am-menu-item',
                onClick: onSelect,
                title: '复制到剪贴板，粘贴进设置页「应用于会话」',
              },
                React.createElement('span', { className: 'am-menu-item-icon' },
                  React.createElement('svg', { viewBox: '0 0 16 16', width: 14, height: 14, fill: 'none', 'aria-hidden': 'true' },
                    React.createElement('rect', { x: 5.5, y: 5.5, width: 8, height: 8, rx: 1.5, stroke: 'currentColor', strokeWidth: 1.2 }),
                    React.createElement('path', { d: 'M10.5 4.5V3.75a.75.75 0 0 0-.75-.75h-6a.75.75 0 0 0-.75.75v6c0 .414.336.75.75.75h.75', stroke: 'currentColor', strokeWidth: 1.2 }),
                  ),
                ),
                React.createElement('span', null, '复制会话 ID'),
              )
            },
          )
        })
      }, 'aire-memory: session menu copy id')

      // 原生设置页里的完整配置页面（settings.section）
      ctx.effect(function () {
        return slots.inject('settings.section', function () {
          return slots.register(
            { name: 'settings.section', id: 'aire-memory', order: 200, label: 'Get记忆' },
            function AireSettingsPage() {
              return React.createElement(SettingsPage)
            },
          )
        })
      }, 'aire-memory: settings section')

      // 插件页的「配置」入口：注册 plugins.row.config 渲染器（键 = 包名#行id）。
      // 注册当前名与正式名两个键，改名期与定名后都能命中。
      var rowConfigKeys = ['dsh-get-memory#aire-memory', '@dsh-external/dsh-aire-memory-v9#aire-memory', '@dsh-external/dsh-aire-memory-v8#aire-memory', '@dsh-external/dsh-aire-memory#aire-memory']
      for (var i = 0; i < rowConfigKeys.length; i += 1) {
        ;(function (rowKey) {
          ctx.effect(function () {
            return slots.inject('plugins.row.config', function () {
              return slots.register(
                { name: 'plugins.row.config', key: rowKey },
                function AireRowConfig() {
                  return React.createElement(MemoryPanel)
                },
              )
            })
          }, 'aire-memory: row config ' + rowKey)
        })(rowConfigKeys[i])
      }

      if (config && config.showTurnIndicators !== false) {
        ctx.effect(function () {
          return slots.inject('conversation.chat.turnTail', function () {
            return slots.register(
              { name: 'conversation.chat.turnTail', id: 'aire-memory-turn', order: 10, label: 'Get记忆' },
              function AireTurnIndicator(props) {
                return React.createElement(TurnMemoryIndicator, props)
              },
            )
          })
        }, 'aire-memory: turn indicator')
      }

      if (config && config.showPanelIcon === false) return

      ctx.effect(function () {
        return slots.inject('sidebar.panellist', function () {
          return slots.register(
            { name: 'sidebar.panellist', id: PANEL_KEY, order: 300, label: 'Get记忆' },
            function AirePanelIcon(props) {
              return React.createElement(AireIcon, { size: (props && props.size) || 20, active: !!(props && props.active) })
            },
          )
        })
      }, 'aire-memory: panel icon')

      ctx.effect(function () {
        return slots.inject('main', function () {
          return slots.register(
            { name: 'main', key: PANEL_KEY },
            function AireMemoryPanel() {
              return React.createElement(MemoryPanel)
            },
          )
        })
      }, 'aire-memory: main panel')
    }

    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
