// Generated by scripts/build-client.mjs from src/client/. Edit those files.
//
// dsh-aire-memory — Aire 记忆（Client）: 右栏快捷面板 + 原生设置页补强。
// 客户端半边是纯 JavaScript（无 JSX、无 ESM import），React 通过闭包注入。
window.__ModuleLoader__.load({
  id: 'dsh-get-memory',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    var React = require('react')

    // Layer: identity and shared constants.
    var PACKAGE = 'dsh-get-memory'
    var STATUS_URL = '/aire-memory/status'
    var PULL_URL = '/aire-memory/pull'
    var WRITEBACK_URL = '/aire-memory/writeback'
    var TOKEN_URL = '/aire-memory/token'
    var CONFIG_URL = '/aire-memory/config'
    var FILESYNC_URL = '/aire-memory/filesync'
    var TOKEN_REF = 'AIRE_MEMORY_GITHUB_TOKEN'
    var PANEL_KEY = 'aire-memory'
    var STYLE_ID = 'dsh-aire-memory-style'

    // Layer: host endpoint calls (状态 / 拉取 / 令牌 / 配置都走宿主半边端点).
    function fetchJson(url, options) {
      return fetch(url, options).then(function (response) {
        if (!response.ok) throw new Error('HTTP ' + response.status)
        return response.json()
      })
    }

    function postJson(url, payload) {
      return fetchJson(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })
    }

    function fetchStatus() {
      return fetchJson(STATUS_URL)
    }

    function triggerPull() {
      return fetchJson(PULL_URL, { method: 'POST' })
    }

    function saveToken(value) {
      return postJson(TOKEN_URL, { token: value })
    }

    function updateConfig(patch) {
      return postJson(CONFIG_URL, { patch: patch })
    }

    function syncFiles() {
      return fetchJson(FILESYNC_URL)
    }

    function saveFileModes(modes) {
      return postJson(FILESYNC_URL, { modes: modes })
    }

    function formatTime(iso) {
      if (!iso) return '—'
      var date = new Date(iso)
      if (Number.isNaN(date.getTime())) return String(iso)
      var pad = function (n) { return n < 10 ? '0' + n : String(n) }
      return date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate())
        + ' ' + pad(date.getHours()) + ':' + pad(date.getMinutes())
    }

    function tokenSourceLabel(source) {
      if (source === 'credentials') return '凭据库'
      if (source === 'env') return '环境变量'
      if (source === 'config') return '插件配置'
      return '其他来源'
    }

    function statusTone(status) {
      if (status === 'ok') return 'ok'
      if (status === 'error') return 'error'
      if (status === 'skip') return 'skip'
      return 'warn'
    }

    // Layer: package stylesheet (plain <style> tag, removed on unload).
    var PANEL_CSS = [
      '.am-panel{display:flex;flex-direction:column;gap:14px;padding:20px;height:100%;overflow-y:auto;box-sizing:border-box;width:100%;max-width:780px;margin:0 auto}',
      '.am-card{background:color-mix(in srgb, var(--ds-color-bg-card,#ffffff) 52%, transparent);backdrop-filter:blur(14px) saturate(1.15);-webkit-backdrop-filter:blur(14px) saturate(1.15);border:1px solid color-mix(in srgb, var(--ds-color-border,#e5e7eb) 62%, transparent);border-radius:14px;padding:14px 16px;box-shadow:0 6px 24px rgba(0,0,0,.06);animation:amFadeIn .28s ease both}',
      '@keyframes amFadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}',
      '.am-title{font-size:13px;font-weight:600;margin:0 0 10px;display:flex;align-items:center;gap:6px}',
      '.am-title .am-pulse{width:7px;height:7px;border-radius:50%;background:#22c55e;animation:amBreathe 2.4s ease-in-out infinite}',
      '@keyframes amBreathe{0%,100%{box-shadow:0 0 0 3px rgba(34,197,94,.18)}50%{box-shadow:0 0 0 6px rgba(34,197,94,.05)}}',
      '.am-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:6px 0}',
      '.am-label{font-size:13px;color:var(--ds-color-text-secondary,#6b7280);flex:none}',
      '.am-value{font-size:13px;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:60%}',
      '.am-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;vertical-align:middle;flex:none}',
      '.am-dot.ok{background:#22c55e}.am-dot.warn{background:#f59e0b}.am-dot.error{background:#ef4444}.am-dot.skip{background:#9ca3af}',
      '.am-history{display:flex;flex-direction:column;gap:8px;max-height:280px;overflow-y:auto}',
      '.am-history-item{font-size:12px;line-height:1.5;display:flex;gap:6px;align-items:baseline}',
      '.am-history-item>span:last-child{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
      '.am-history-time{color:var(--ds-color-text-tertiary,#9ca3af);flex:none}',
      '.am-history-kind{flex:none;font-size:11px;padding:0 5px;border-radius:4px;background:color-mix(in srgb, var(--ds-color-bg-secondary,#f3f4f6) 72%, transparent);color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-input{flex:1;min-width:0;font-size:13px;padding:6px 8px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-input,#ffffff) 60%, transparent);color:inherit;transition:border-color .15s}',
      '.am-input:focus{border-color:var(--ds-color-accent,#4f46e5);outline:none}',
      '.am-textarea{flex:1;min-width:0;font-size:13px;padding:6px 8px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-input,#ffffff) 60%, transparent);color:inherit;resize:vertical;font-family:inherit;line-height:1.5}',
      '.am-button{font-size:13px;padding:6px 12px;border-radius:8px;border:1px solid var(--ds-color-border,#e5e7eb);background:color-mix(in srgb, var(--ds-color-bg-secondary,#f3f4f6) 80%, transparent);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);color:inherit;cursor:pointer;transition:filter .15s,transform .05s;flex:none}',
      '.am-button:hover:not(:disabled){filter:brightness(.96)}',
      '.am-button:active:not(:disabled){transform:scale(.98)}',
      '.am-button.primary{background:var(--ds-color-accent,#4f46e5);border-color:transparent;color:#fff}',
      '.am-button.primary:hover:not(:disabled){filter:brightness(1.08)}',
      '.am-button:disabled{opacity:.55;cursor:default}',
      '.am-notice{font-size:12px;color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-empty{font-size:12px;color:var(--ds-color-text-tertiary,#9ca3af);padding:6px 0}',
      '.am-switch{position:relative;width:36px;height:20px;border-radius:999px;border:1px solid var(--ds-color-border,#e5e7eb);background:var(--ds-color-bg-secondary,#e5e7eb);cursor:pointer;flex:none;transition:background .15s}',
      '.am-switch.on{background:var(--ds-color-accent,#4f46e5);border-color:transparent}',
      '.am-switch::after{content:"";position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;background:#fff;transition:left .15s}',
      '.am-switch.on::after{left:18px}',
      '.am-switch:focus-visible{outline:2px solid var(--ds-color-accent,#4f46e5);outline-offset:2px}',
      '.am-indicator{display:inline-flex;align-items:center;gap:6px;font-size:12px;color:var(--ds-color-text-tertiary,#9ca3af);padding:2px 0}',
      '.am-indicator .am-dot{margin-right:0}',
      '.am-indicator:hover{color:var(--ds-color-text-secondary,#6b7280)}',
      '.am-global-notice{display:inline-flex;align-items:center;gap:7px;font-size:12px;color:var(--ds-color-text-secondary,#6b7280);background:color-mix(in srgb, var(--ds-color-bg-card,#ffffff) 72%, transparent);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);border:1px solid color-mix(in srgb, var(--ds-color-border,#e5e7eb) 60%, transparent);border-radius:999px;padding:4px 12px;animation:amFadeIn .28s ease both}',
      '.am-global-notice .am-dot{margin-right:0}',
    ].join('\n')

    function installStyles() {
      if (document.getElementById(STYLE_ID)) return function () {}
      var tag = document.createElement('style')
      tag.id = STYLE_ID
      tag.setAttribute('data-dyn', PACKAGE)
      tag.textContent = PANEL_CSS
      document.head.append(tag)
      return function () { tag.remove() }
    }

    // Layer: panel icon and the main Aire 记忆 panel.
    function AireIcon(props) {
      var size = props && props.size ? props.size : 20
      var active = !!(props && props.active)
      return React.createElement(
        'svg',
        {
          width: size, height: size, viewBox: '0 0 24 24', fill: 'none',
          'aria-hidden': 'true',
        },
        React.createElement('path', {
          d: 'M12 21s-7.5-4.6-9.7-9.3C.7 8.3 2.7 4.5 6.3 4.5c2.2 0 3.7 1.2 5.7 3.4 2-2.2 3.5-3.4 5.7-3.4 3.6 0 5.6 3.8 4 7.2C19.5 16.4 12 21 12 21z',
          fill: active ? 'currentColor' : 'none',
          stroke: 'currentColor',
          strokeWidth: 1.6,
          strokeLinejoin: 'round',
          opacity: active ? 1 : 0.75,
        }),
      )
    }

    function StatusDot(props) {
      return React.createElement('span', { className: 'am-dot ' + statusTone(props.status) })
    }

    function Card(props) {
      return React.createElement('div', { className: 'am-card' },
        React.createElement('div', { className: 'am-title' }, props.title),
        props.children,
      )
    }

    function Row(props) {
      return React.createElement('div', { className: 'am-row' },
        React.createElement('span', { className: 'am-label' }, props.label),
        props.children,
      )
    }

    function Switch(props) {
      return React.createElement('button', {
        type: 'button',
        className: 'am-switch' + (props.on ? ' on' : ''),
        'aria-pressed': !!props.on,
        title: props.title,
        onClick: props.onToggle,
        disabled: props.disabled,
      })
    }

    function Button(props) {
      return React.createElement('button', {
        type: 'button',
        className: 'am-button' + (props.primary ? ' primary' : ''),
        onClick: props.onClick,
        disabled: props.disabled,
      }, props.children)
    }

    function HistoryList(props) {
      var history = props.history
      if (!Array.isArray(history) || history.length === 0) {
        return React.createElement('div', { className: 'am-empty' }, '还没有操作记录')
      }
      return React.createElement('div', { className: 'am-history' },
        history.map(function (entry, index) {
          var kindLabel = entry.kind === 'pull' ? '拉取'
            : entry.kind === 'writeback' ? '写回'
            : entry.kind === 'config' ? '配置'
            : entry.kind === 'token' ? '令牌'
            : entry.kind === 'discover' ? '发现'
            : String(entry.kind || '记录')
          return React.createElement('div', { className: 'am-history-item', key: index },
            React.createElement('span', { className: 'am-history-time' }, formatTime(entry.at)),
            React.createElement('span', { className: 'am-history-kind' }, kindLabel),
            React.createElement(StatusDot, { status: statusTone(entry.status) }),
            React.createElement('span', null, entry.message || ''),
          )
        }),
      )
    }

    function MemoryPanel() {
      var statePair = React.useState(null)
      var status = statePair[0]
      var setStatus = statePair[1]
      var busyPair = React.useState(false)
      var busy = busyPair[0]
      var setBusy = busyPair[1]
      var noticePair = React.useState('')
      var notice = noticePair[0]
      var setNotice = noticePair[1]
      var draftPair = React.useState('')
      var draft = draftPair[0]
      var setDraft = draftPair[1]

      var refresh = function () {
        fetchStatus().then(setStatus, function (error) {
          setStatus({ ok: false, error: String((error && error.message) || error) })
        })
      }

      React.useEffect(function () {
        refresh()
        var timer = setInterval(refresh, 5000)
        return function () { clearInterval(timer) }
      }, [])

      var flash = function (text) {
        setNotice(text)
        setTimeout(function () { setNotice('') }, 4000)
      }

      var onPull = function () {
        if (busy) return
        setBusy(true)
        triggerPull().then(function (next) {
          setStatus(next)
          setBusy(false)
          flash(next && next.pullOk ? '拉取完成' : '拉取没有完全成功，看状态卡片')
        }, function (error) {
          setBusy(false)
          flash('拉取失败：' + String((error && error.message) || error))
        })
      }

      var onSaveToken = function () {
        var value = String(draft || '').trim()
        if (!value) { flash('先粘贴令牌再点保存'); return }
        setBusy(true)
        saveToken(value).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setDraft('')
            if (result.verified) {
              flash('令牌已保存，仓库验证通过')
            } else {
              flash('令牌已保存，但仓库验证失败：' + (result.verifyMessage || '未知原因'))
            }
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
          setTimeout(refresh, 600)
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onToggleWriteback = function () {
        var current = !!(status && status.writebackEnabled)
        setBusy(true)
        updateConfig({ writebackEnabled: !current }).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash(!current ? '自动写回已开启' : '自动写回已关闭')
            setTimeout(refresh, 800)
          } else {
            flash('切换失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('切换失败：' + String((error && error.message) || error))
        })
      }

      if (status && status.ok === false) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement(Card, { title: 'Get记忆' },
            React.createElement('div', { className: 'am-notice' }, '无法读取插件状态：' + (status.error || '未知错误')),
          ),
        )
      }

      var token = (status && status.token) || { configured: false, source: null }
      var cache = status && status.cache
      var lastWriteback = status && status.lastWriteback

      return React.createElement('div', { className: 'am-panel' },
        React.createElement(Card, { title: React.createElement(React.Fragment, null,
          React.createElement(AireIcon, { size: 16 }),
          'Get记忆 · ' + ((status && status.repo) || ''),
          status && status.ok ? React.createElement('span', { className: 'am-pulse', title: '插件在线' }) : null,
        ) },
          React.createElement(Row, { label: '记忆仓库' },
            React.createElement('span', { className: 'am-value' },
              status ? (status.repo + '@' + status.branch) : '…'),
          ),
          React.createElement(Row, { label: '最近拉取' },
            React.createElement('span', { className: 'am-value' },
              cache ? formatTime(cache.fetchedAt) + (cache.stale ? '（部分过期）' : '') : '尚未拉取'),
          ),
          React.createElement(Row, { label: '最近写回' },
            React.createElement('span', { className: 'am-value' },
              lastWriteback
                ? formatTime(lastWriteback.at) + ' · ' + (lastWriteback.phase === 'committed' ? '已提交' : lastWriteback.phase === 'skipped' ? '跳过' : lastWriteback.phase === 'error' ? '失败' : lastWriteback.phase)
                : '—'),
          ),
          React.createElement(Row, { label: '自动写回' },
            React.createElement(Switch, {
              on: !!status && !!status.writebackEnabled,
              onToggle: onToggleWriteback,
              disabled: busy || !status,
              title: '对话结束自动提取记忆写回仓库',
            }),
          ),
        ),

        React.createElement(Card, { title: '令牌' },
          React.createElement(Row, { label: '当前状态' },
            React.createElement('span', { className: 'am-value' },
              token.configured ? '已配置（' + tokenSourceLabel(token.source) + '）' : '未配置'),
          ),
          React.createElement('div', { className: 'am-row' },
            React.createElement('input', {
              className: 'am-input',
              type: 'password',
              placeholder: token.configured ? '留空保持不变，粘贴新令牌可替换' : '粘贴 GitHub 细颗粒度令牌（仅本仓库 Contents 读写）',
              value: draft,
              onChange: function (event) { setDraft(event.target.value) },
            }),
            React.createElement(Button, { primary: true, onClick: onSaveToken, disabled: busy }, '保存'),
          ),
          React.createElement('div', { className: 'am-notice' }, '令牌存入 DSH 凭据库，绝不写入记忆仓库'),
        ),

        React.createElement(Card, { title: '操作' },
          React.createElement(Row, { label: '立刻从仓库拉取最新记忆' },
            React.createElement(Button, { primary: true, onClick: onPull, disabled: busy }, busy ? '处理中…' : '立即拉取'),
          ),
          React.createElement(Row, { label: '完整配置' },
            React.createElement('span', { className: 'am-notice' }, '打开 DSH 设置 → 「Get记忆」页面，仓库、文件、防抖时长等全部字段都能在那里调整'),
          ),
        ),

        React.createElement(Card, { title: '最近记录' },
          React.createElement(HistoryList, { history: status && status.history }),
        ),

        notice
          ? React.createElement('div', { className: 'am-notice' }, notice)
          : null,
      )
    }

    // Layer: 每回合结束处的记忆写回指示（conversation.chat.turnTail）。
    var INDICATOR_TIMEOUT_MS = 90000
    var INDICATOR_POLL_MS = 3000

    function fetchWriteback(sessionId, turn, seq) {
      var params = new URLSearchParams()
      params.set('session', String(sessionId === undefined || sessionId === null ? '' : sessionId))
      if (turn !== undefined && turn !== null) params.set('turn', String(turn))
      if (seq !== undefined && seq !== null) params.set('seq', String(seq))
      return fetchJson(WRITEBACK_URL + '?' + params.toString())
    }

    function TurnMemoryIndicator(props) {
      var sessionId = props && props.sessionId
      var turnProp = props && props.turn
      var turn = (typeof turnProp === 'object' && turnProp !== null) ? turnProp.turn : turnProp
      var seq = props && props.seq

      var recordPair = React.useState(null)
      var record = recordPair[0]
      var setRecord = recordPair[1]
      var livePair = React.useState(true)
      var live = livePair[0]
      var setLive = livePair[1]

      React.useEffect(function () {
        var stop = false
        var settled = false
        var started = Date.now()

        var check = function () {
          if (stop) return
          fetchWriteback(sessionId, turn, seq).then(function (data) {
            if (stop) return
            if (data && data.found === true && data.record) {
              setRecord(data.record)
              if (data.record.phase === 'committed' || data.record.phase === 'skipped' || data.record.phase === 'error') {
                settled = true
              }
            } else if (Date.now() - started > INDICATOR_TIMEOUT_MS) {
              setLive(false)
            }
          }, function () {
            if (Date.now() - started > INDICATOR_TIMEOUT_MS) setLive(false)
          })
        }

        check()
        var timer = setInterval(function () {
          if (stop || settled) return
          if (Date.now() - started > INDICATOR_TIMEOUT_MS) { setLive(false); return }
          check()
        }, INDICATOR_POLL_MS)

        return function () {
          stop = true
          clearInterval(timer)
        }
      }, [sessionId, turn, seq])

      if (!live || !record) return null

      var text = null
      var tone = null
      if (record.phase === 'attempt') { text = '记忆整理中…'; tone = 'warn' }
      else if (record.phase === 'committed') { text = '记忆已写回 ✓'; tone = 'ok' }
      else if (record.phase === 'skipped') { text = '无新记忆'; tone = 'skip' }
      else if (record.phase === 'error') { text = '记忆写回失败'; tone = 'error' }
      if (text === null) return null

      var detail = record.summary || record.message || ''
      return React.createElement('div', {
        className: 'am-indicator',
        title: detail,
      },
        React.createElement(StatusDot, { status: tone }),
        React.createElement('span', null, 'Get记忆 · ' + text),
      )
    }

    // Layer: 原生设置页里的完整配置页面（settings.section）。
    function FieldRow(props) {
      return React.createElement('div', { className: 'am-row' },
        React.createElement('span', { className: 'am-label' }, props.label),
        props.children,
      )
    }

    function TextField(props) {
      return React.createElement('input', {
        className: 'am-input',
        type: props.type || 'text',
        value: props.value === undefined || props.value === null ? '' : String(props.value),
        placeholder: props.placeholder || '',
        onChange: function (event) { props.onChange(event.target.value) },
      })
    }

    function TextAreaField(props) {
      return React.createElement('textarea', {
        className: 'am-input am-textarea',
        rows: 3,
        value: props.value === undefined || props.value === null ? '' : String(props.value),
        placeholder: props.placeholder || '',
        onChange: function (event) { props.onChange(event.target.value) },
      })
    }

    function NumberField(props) {
      return React.createElement('input', {
        className: 'am-input',
        type: 'number',
        value: props.value === undefined || props.value === null ? '' : String(props.value),
        onChange: function (event) { props.onChange(Number(event.target.value)) },
      })
    }

    function SettingsPage() {
      var statePair = React.useState(null)
      var status = statePair[0]
      var setStatus = statePair[1]
      var busyPair = React.useState(false)
      var busy = busyPair[0]
      var setBusy = busyPair[1]
      var noticePair = React.useState('')
      var notice = noticePair[0]
      var setNotice = noticePair[1]

      var formPair = React.useState(null)
      var form = formPair[0]
      var setForm = formPair[1]
      var tokenDraftPair = React.useState('')
      var tokenDraft = tokenDraftPair[0]
      var setTokenDraft = tokenDraftPair[1]

      var refresh = function () {
        fetchStatus().then(function (next) {
          setStatus(next)
          if (next && next.settings && form === null) setForm(cloneForm(next.settings))
        }, function (error) {
          setStatus({ ok: false, error: String((error && error.message) || error) })
        })
      }

      React.useEffect(function () {
        refresh()
        var timer = setInterval(refresh, 8000)
        return function () { clearInterval(timer) }
      }, [])

      var flash = function (text) {
        setNotice(text)
        setTimeout(function () { setNotice('') }, 5000)
      }

      var setField = function (key, value) {
        setForm(function (current) {
          var next = Object.assign({}, current || {})
          next[key] = value
          return next
        })
      }

      // ---- 文件权限中心 ----
      var fileSyncPair = React.useState(null)
      var fileSync = fileSyncPair[0]
      var setFileSync = fileSyncPair[1]

      var onSyncFiles = function () {
        if (busy) return
        setBusy(true)
        syncFiles().then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setFileSync({ files: result.files, removed: result.removed })
            flash('文件列表已同步（' + (result.files ? result.files.length : 0) + ' 个文件）')
          } else {
            flash('同步失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('同步失败：' + String((error && error.message) || error))
        })
      }

      var onToggleFileMode = function (file) {
        setFileSync(function (current) {
          if (!current) return current
          var files = (current.files || []).map(function (entry) {
            if (entry.file !== file) return entry
            return Object.assign({}, entry, { mode: entry.mode === 'rw' ? 'ro' : 'rw' })
          })
          return { files: files, removed: current.removed }
        })
      }

      var onApplyFileModes = function () {
        if (!fileSync) return
        setBusy(true)
        var modes = (fileSync.files || []).map(function (entry) { return { file: entry.file, mode: entry.mode } })
        saveFileModes(modes).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash('文件权限已应用（' + (result.applied || 0) + ' 个）')
            setTimeout(refresh, 600)
          } else {
            flash('应用失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('应用失败：' + String((error && error.message) || error))
        })
      }

      var onSave = function () {
        if (!form) return
        setBusy(true)
        var patch = {}
        patch.repo = String(form.repo || '').trim()
        patch.branch = String(form.branch || '').trim()
        patch.ledgerFile = String(form.ledgerFile || '').trim()
        patch.injectOrder = Number(form.injectOrder)
        patch.writebackEnabled = !!form.writebackEnabled
        patch.writebackDebounceMs = Number(form.writebackDebounceMs)
        patch.maxTranscriptChars = Number(form.maxTranscriptChars)
        patch.minConversationChars = Number(form.minConversationChars)
        patch.extractProvider = String(form.extractProvider || '').trim()
        patch.extractModel = String(form.extractModel || '').trim()
        patch.requestTimeoutMs = Number(form.requestTimeoutMs)
        patch.historyLimit = Number(form.historyLimit)
        patch.autoDiscoverFiles = !!form.autoDiscoverFiles
        patch.writebackEveryN = Math.max(1, Number(form.writebackEveryN) || 1)
        patch.sessionPolicyMode = form.sessionPolicyMode === 'exclude' || form.sessionPolicyMode === 'include' ? form.sessionPolicyMode : 'all'
        patch.sessionPolicyIds = String(form.sessionPolicyIds || '')
          .split('\n').map(function (line) { return line.trim() }).filter(Boolean)
        patch.showGlobalNotice = !!form.showGlobalNotice
        patch.maxWriteFiles = Math.max(1, Number(form.maxWriteFiles) || 5)
        updateConfig(patch).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            flash('设置已保存并生效')
            setTimeout(refresh, 600)
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onSaveToken = function () {
        var value = String(tokenDraft || '').trim()
        if (!value) { flash('先粘贴令牌再点保存'); return }
        setBusy(true)
        saveToken(value).then(function (result) {
          setBusy(false)
          if (result && result.ok) {
            setTokenDraft('')
            flash(result.verified ? '令牌已保存，仓库验证通过' : '令牌已保存，但仓库验证失败：' + (result.verifyMessage || ''))
            setTimeout(refresh, 600)
          } else {
            flash('保存失败：' + ((result && result.message) || '未知错误'))
          }
        }, function (error) {
          setBusy(false)
          flash('保存失败：' + String((error && error.message) || error))
        })
      }

      var onPull = function () {
        if (busy) return
        setBusy(true)
        triggerPull().then(function (next) {
          setBusy(false)
          setStatus(next)
          flash(next && next.pullOk ? '拉取完成' : '拉取没有完全成功，看状态卡片')
        }, function (error) {
          setBusy(false)
          flash('拉取失败：' + String((error && error.message) || error))
        })
      }

      if (!status) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement('div', { className: 'am-notice' }, '读取插件状态中…'),
        )
      }

      if (status.ok === false) {
        return React.createElement('div', { className: 'am-panel' },
          React.createElement('div', { className: 'am-notice' }, '无法读取插件状态：' + (status.error || '未知错误')),
        )
      }

      var token = status.token || { configured: false, source: null }
      var cache = status.cache
      var lastWriteback = status.lastWriteback

      return React.createElement('div', { className: 'am-panel am-settings' },
        React.createElement(Card, { title: '状态' },
          React.createElement(Row, { label: '最近拉取' },
            React.createElement('span', { className: 'am-value' },
              cache ? formatTime(cache.fetchedAt) + (cache.stale ? '（部分过期）' : '') : '尚未拉取'),
          ),
          React.createElement(Row, { label: '最近写回' },
            React.createElement('span', { className: 'am-value' },
              lastWriteback
                ? formatTime(lastWriteback.at) + ' · ' + (lastWriteback.phase === 'committed' ? '已提交' : lastWriteback.phase === 'skipped' ? '跳过' : lastWriteback.phase === 'error' ? '失败' : lastWriteback.phase)
                : '—'),
          ),
          React.createElement(Row, { label: '操作' },
            React.createElement(Button, { primary: true, onClick: onPull, disabled: busy }, busy ? '处理中…' : '立即拉取'),
          ),
        ),

        React.createElement(Card, { title: '令牌' },
          React.createElement(Row, { label: '当前状态' },
            React.createElement('span', { className: 'am-value' },
              token.configured ? '已配置（' + tokenSourceLabel(token.source) + '）' : '未配置'),
          ),
          React.createElement('div', { className: 'am-row' },
            React.createElement('input', {
              className: 'am-input',
              type: 'password',
              placeholder: token.configured ? '留空保持不变，粘贴新令牌可替换' : '粘贴 GitHub 细颗粒度令牌（仅目标仓库 Contents 读写）',
              value: tokenDraft,
              onChange: function (event) { setTokenDraft(event.target.value) },
            }),
            React.createElement(Button, { primary: true, onClick: onSaveToken, disabled: busy }, '保存'),
          ),
          React.createElement('div', { className: 'am-notice' }, '令牌存入 DSH 凭据库，绝不写入记忆仓库'),
        ),

        React.createElement(Card, { title: '记忆仓库' },
          React.createElement(FieldRow, { label: '仓库（owner/repo）' },
            React.createElement(TextField, { value: form ? form.repo : '', onChange: function (v) { setField('repo', v) } }),
          ),
          React.createElement(FieldRow, { label: '分支' },
            React.createElement(TextField, { value: form ? form.branch : '', onChange: function (v) { setField('branch', v) } }),
          ),
          React.createElement(FieldRow, { label: '主账本文件' },
            React.createElement(TextField, { value: form ? form.ledgerFile : '', onChange: function (v) { setField('ledgerFile', v) } }),
          ),
        ),

        React.createElement(Card, { title: '文件权限' },
          React.createElement(Row, { label: '同步仓库文件列表' },
            React.createElement(Button, { primary: true, onClick: onSyncFiles, disabled: busy }, busy ? '同步中…' : '同步文件列表'),
          ),
          fileSync && fileSync.files
            ? fileSync.files.map(function (entry) {
                return React.createElement(Row, { label: React.createElement(React.Fragment, null,
                  entry.file,
                  entry.isNew ? React.createElement('span', { className: 'am-notice', key: 'n' }, '（新）') : null,
                ) },
                  React.createElement('div', { className: 'am-row' },
                    React.createElement(Button, {
                      primary: entry.mode === 'rw',
                      onClick: function () { if (entry.mode !== 'rw') onToggleFileMode(entry.file) },
                    }, '读写'),
                    React.createElement(Button, {
                      primary: entry.mode === 'ro',
                      onClick: function () { if (entry.mode !== 'ro') onToggleFileMode(entry.file) },
                    }, '只读'),
                  ),
                )
              })
            : React.createElement('div', { className: 'am-empty' }, '点「同步文件列表」拉取仓库当前文件'),
          fileSync && fileSync.removed && fileSync.removed.length > 0
            ? React.createElement('div', { className: 'am-notice' }, '已删除（将从权限表移除）：' + fileSync.removed.join('、'))
            : null,
          fileSync && fileSync.files && fileSync.files.length > 0
            ? React.createElement(Row, { label: '应用以上权限' },
                React.createElement(Button, { primary: true, onClick: onApplyFileModes, disabled: busy }, '应用'),
              )
            : null,
          React.createElement('div', { className: 'am-notice' }, '「只读」仅注入上下文；「读写」在对话结束后也会作为写回目标（新文件默认读写）'),
        ),

        React.createElement(Card, { title: '写回与提取' },
          React.createElement(Row, { label: '自动写回' },
            React.createElement(Switch, {
              on: form ? !!form.writebackEnabled : false,
              onToggle: function () { setField('writebackEnabled', !(form && form.writebackEnabled)) },
              disabled: busy,
            }),
          ),
          React.createElement(FieldRow, { label: '写回防抖（毫秒）' },
            React.createElement(NumberField, { value: form ? form.writebackDebounceMs : 0, onChange: function (v) { setField('writebackDebounceMs', v) } }),
          ),
          React.createElement(FieldRow, { label: '转录上限（字符）' },
            React.createElement(NumberField, { value: form ? form.maxTranscriptChars : 0, onChange: function (v) { setField('maxTranscriptChars', v) } }),
          ),
          React.createElement(FieldRow, { label: '最低转录长度' },
            React.createElement(NumberField, { value: form ? form.minConversationChars : 0, onChange: function (v) { setField('minConversationChars', v) } }),
          ),
          React.createElement(FieldRow, { label: '提取模型 provider' },
            React.createElement(TextField, { value: form ? form.extractProvider : '', placeholder: '留空用会话模型', onChange: function (v) { setField('extractProvider', v) } }),
          ),
          React.createElement(FieldRow, { label: '提取模型 model' },
            React.createElement(TextField, { value: form ? form.extractModel : '', placeholder: '留空用会话模型', onChange: function (v) { setField('extractModel', v) } }),
          ),
        ),

        React.createElement(Card, { title: '触发与范围' },
          React.createElement(FieldRow, { label: '每 N 次对话写回' },
            React.createElement(NumberField, { value: form ? form.writebackEveryN : 1, onChange: function (v) { setField('writebackEveryN', v) } }),
          ),
          React.createElement(FieldRow, { label: '应用于会话' },
            React.createElement('select', {
              className: 'am-input',
              value: form ? form.sessionPolicyMode : 'all',
              onChange: function (event) { setField('sessionPolicyMode', event.target.value) },
            },
              React.createElement('option', { value: 'all' }, '全部会话'),
              React.createElement('option', { value: 'exclude' }, '排除以下会话'),
              React.createElement('option', { value: 'include' }, '仅以下会话'),
            ),
          ),
          form && form.sessionPolicyMode !== 'all'
            ? React.createElement(FieldRow, { label: '会话 ID（每行一个）' },
                React.createElement(TextAreaField, {
                  value: form.sessionPolicyIds,
                  placeholder: '粘贴会话 ID，每行一个',
                  onChange: function (v) { setField('sessionPolicyIds', v) },
                }),
              )
            : null,
          React.createElement(Row, { label: '写回变动全局提示' },
            React.createElement(Switch, {
              on: form ? form.showGlobalNotice !== false : true,
              onToggle: function () { setField('showGlobalNotice', form ? form.showGlobalNotice === false : false) },
              disabled: busy,
              title: '写回有变动时在输入框上方显示小条提示',
            }),
          ),
          React.createElement(FieldRow, { label: '每次写回最多文件数' },
            React.createElement(NumberField, { value: form ? form.maxWriteFiles : 5, onChange: function (v) { setField('maxWriteFiles', v) } }),
          ),
        ),

        React.createElement(Card, { title: '其他' },
          React.createElement(FieldRow, { label: '注入排序号' },
            React.createElement(NumberField, { value: form ? form.injectOrder : 100, onChange: function (v) { setField('injectOrder', v) } }),
          ),
          React.createElement(FieldRow, { label: '请求超时（毫秒）' },
            React.createElement(NumberField, { value: form ? form.requestTimeoutMs : 15000, onChange: function (v) { setField('requestTimeoutMs', v) } }),
          ),
          React.createElement(FieldRow, { label: '记录保留条数' },
            React.createElement(NumberField, { value: form ? form.historyLimit : 50, onChange: function (v) { setField('historyLimit', v) } }),
          ),
          React.createElement(Row, { label: '自动发现新文件' },
            React.createElement(Switch, {
              on: form ? form.autoDiscoverFiles !== false : true,
              onToggle: function () { setField('autoDiscoverFiles', form ? form.autoDiscoverFiles === false : false) },
              disabled: busy,
              title: '每次拉取时把仓库根目录新出现的 .md 文件自动加入注入列表',
            }),
          ),
        ),

        React.createElement('div', { className: 'am-row' },
          React.createElement(Button, { primary: true, onClick: onSave, disabled: busy || !form }, busy ? '保存中…' : '保存全部设置'),
        ),
        notice ? React.createElement('div', { className: 'am-notice' }, notice) : null,
      )
    }

    function cloneForm(settings) {
      return {
        repo: settings.repo,
        branch: settings.branch,
        ledgerFile: settings.ledgerFile,
        injectOrder: settings.injectOrder,
        writebackEnabled: settings.writebackEnabled,
        writebackDebounceMs: settings.writebackDebounceMs,
        maxTranscriptChars: settings.maxTranscriptChars,
        minConversationChars: settings.minConversationChars,
        extractProvider: settings.extractProvider,
        extractModel: settings.extractModel,
        requestTimeoutMs: settings.requestTimeoutMs,
        historyLimit: settings.historyLimit,
        autoDiscoverFiles: settings.autoDiscoverFiles,
        writebackEveryN: settings.writebackEveryN,
        sessionPolicyMode: settings.sessionPolicyMode,
        sessionPolicyIds: Array.isArray(settings.sessionPolicyIds) ? settings.sessionPolicyIds.join('\n') : '',
        showGlobalNotice: settings.showGlobalNotice,
        maxWriteFiles: settings.maxWriteFiles,
      }
    }

    // Layer: 全局提示——写回有变动时在输入框下方显示小条（几秒后消失，简洁模式也可见）。
    function GlobalMemoryNotice() {
      var shownPair = React.useState(null)
      var shown = shownPair[0]
      var setShown = shownPair[1]
      var lastSeenPair = React.useRef(null)

      React.useEffect(function () {
        var alive = true
        var hideTimer = null
        var poll = function () {
          fetchStatus().then(function (status) {
            if (!alive || !status || status.ok === false) return
            if (status.settings && status.settings.showGlobalNotice === false) {
              setShown(null)
              return
            }
            var wb = status.lastWriteback
            if (wb && wb.phase === 'committed' && wb.at) {
              if (lastSeenPair.current !== wb.at) {
                lastSeenPair.current = wb.at
                setShown(wb.summary || '记忆已更新')
                if (hideTimer) clearTimeout(hideTimer)
                hideTimer = setTimeout(function () { if (alive) setShown(null) }, 12000)
              }
            }
          }, function () { /* 网络抖动忽略 */ })
        }
        poll()
        var interval = setInterval(poll, 5000)
        return function () {
          alive = false
          clearInterval(interval)
          if (hideTimer) clearTimeout(hideTimer)
        }
      }, [])

      if (!shown) return null
      return React.createElement('div', { className: 'am-global-notice', role: 'status' },
        React.createElement(StatusDot, { status: 'ok' }),
        React.createElement('span', null, shown),
      )
    }

    // Layer: mount the right-rail icon, the main panel, the Plugins-page row config page, and package styles; all reversible.
    var name = 'dsh-aire-memory'
    var inject = ['slots']

    function apply(ctx, config) {
      var slots = ctx.get('slots')
      if (slots === undefined || React === undefined) return

      ctx.effect(installStyles, 'aire-memory: styles')

      // 全局提示：写回有变动时在输入框下方显示小条（conversation.composer.dock）
      ctx.effect(function () {
        return slots.inject('conversation.composer.dock', function () {
          return slots.register(
            { name: 'conversation.composer.dock', id: 'aire-memory-notice', order: 20, label: 'Get记忆' },
            function AireGlobalNotice() {
              return React.createElement(GlobalMemoryNotice)
            },
          )
        })
      }, 'aire-memory: global notice')

      // 原生设置页里的完整配置页面（settings.section）
      ctx.effect(function () {
        return slots.inject('settings.section', function () {
          return slots.register(
            { name: 'settings.section', id: 'aire-memory', order: 200, label: 'Get记忆' },
            function AireSettingsPage() {
              return React.createElement(SettingsPage)
            },
          )
        })
      }, 'aire-memory: settings section')

      // 插件页的「配置」入口：注册 plugins.row.config 渲染器（键 = 包名#行id）。
      // 注册当前名与正式名两个键，改名期与定名后都能命中。
      var rowConfigKeys = ['dsh-get-memory#aire-memory', '@dsh-external/dsh-aire-memory-v9#aire-memory', '@dsh-external/dsh-aire-memory-v8#aire-memory', '@dsh-external/dsh-aire-memory#aire-memory']
      for (var i = 0; i < rowConfigKeys.length; i += 1) {
        ;(function (rowKey) {
          ctx.effect(function () {
            return slots.inject('plugins.row.config', function () {
              return slots.register(
                { name: 'plugins.row.config', key: rowKey },
                function AireRowConfig() {
                  return React.createElement(MemoryPanel)
                },
              )
            })
          }, 'aire-memory: row config ' + rowKey)
        })(rowConfigKeys[i])
      }

      if (config && config.showTurnIndicators !== false) {
        ctx.effect(function () {
          return slots.inject('conversation.chat.turnTail', function () {
            return slots.register(
              { name: 'conversation.chat.turnTail', id: 'aire-memory-turn', order: 10, label: 'Get记忆' },
              function AireTurnIndicator(props) {
                return React.createElement(TurnMemoryIndicator, props)
              },
            )
          })
        }, 'aire-memory: turn indicator')
      }

      if (config && config.showPanelIcon === false) return

      ctx.effect(function () {
        return slots.inject('sidebar.panellist', function () {
          return slots.register(
            { name: 'sidebar.panellist', id: PANEL_KEY, order: 300, label: 'Get记忆' },
            function AirePanelIcon(props) {
              return React.createElement(AireIcon, { size: (props && props.size) || 20, active: !!(props && props.active) })
            },
          )
        })
      }, 'aire-memory: panel icon')

      ctx.effect(function () {
        return slots.inject('main', function () {
          return slots.register(
            { name: 'main', key: PANEL_KEY },
            function AireMemoryPanel() {
              return React.createElement(MemoryPanel)
            },
          )
        })
      }, 'aire-memory: main panel')
    }

    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
