#!/usr/bin/env node
// Concatenate src/client/*.js into the DSH ModuleLoader bundle at client.js.
// Browser half cannot use ESM imports; this is the only supported split.
// (Pattern follows the official dsh-liquid-glass client bundling.)

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'src', 'client')
const outFile = join(root, 'client.js')

const CLIENT_LAYERS = [
  'constants.js',
  'api.js',
  'styles.js',
  'components.js',
  'indicator.js',
  'settings-view.js',
  'notice.js',
  'apply.js',
]

const HEADER = `// Generated by scripts/build-client.mjs from src/client/. Edit those files.
//
// dsh-aire-memory — Aire 记忆（Client）: 右栏快捷面板 + 原生设置页补强。
// 客户端半边是纯 JavaScript（无 JSX、无 ESM import），React 通过闭包注入。
window.__ModuleLoader__.load({
  id: 'dsh-get-memory',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    var React = require('react')
`

const FOOTER = `
    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
`

export async function renderClient() {
  const parts = []
  for (const name of CLIENT_LAYERS) {
    const body = await readFile(join(srcDir, name), 'utf8')
    parts.push(body.replace(/\n+$/, ''))
  }
  return HEADER + '\n' + parts.join('\n\n') + '\n' + FOOTER
}

export async function writeClient() {
  const next = await renderClient()
  await writeFile(outFile, next)
  return outFile
}

const invoked = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]
if (invoked) {
  await writeClient()
  console.log('wrote client.js')
}
